@chebfun/mrdivide.m, @chebfun/rdivide.m, tests/chebfun/test_mrdivide.m, tests/chebfun/test_rdivide.m
* These should now all throw an error: `f / 0`, `f ./ 0`, `f ./ [0 0]` and
`f ./ [0 1 0]`.
* Part of this is fixing a bug of the form "if (vector == scalar)".
=> Dividing a chebfun by scalar 0 was handled inconsistently

@chebfun/trigcoeffs.m, tests/chebfun/test_trigcoeffs.m
Added code in `trigcoeffs` to throw an error when the input is a `chebfun` (instead of a `trigfun`) and a value for the number of coefficients has not been specified.
Included a test for this case.
This addresses #1334.
=> Throw error in trigcoeffs when the input is not a trigfun and the number coeffs not specified

@chebop/islinear.m
Make sure that operators with non Frechet differentiable components get marked as nonlinear, rather than an error being thrown.
=> Hotfix display non differentiable

@unbndfun/sum.m, tests/unbndfun/test_sum.m
With reference to #1026, this change and test does the trick of dealing with the accuracy of `sum(f1)`, with the caveat that it feels like the checking for exponents is inelegant and that the tolerance increase to keep all tests passing seems too large.
=> Naively restore exponents before integrating singfun

@bndfun/plotData.m, @chebfun/plot.m, @chebtech/plotData.m, @singfun/plotData.m, @unbndfun/plotData.m, tests/chebfun/test_plot.m, tests/chebfun/test_plot_xylim.m
Fixing a bug for plotting an unbndfun defined on [a Inf] or [-Inf b] which has unbounded function value at the finite endpoint. This bug was reported by Hadrien.
```
g = chebfun(@(x) 1./x.^2, [0 Inf], 'exps', [-2 0]); plot(g)
```
Before:
After:
=> Fixing a bug for plotting an unbndfun

@bndfun/fracInt.m, @chebfun/chebfun.m, @chebfun/cumsum.m, @chebfun/diff.m, @chebfun/fracDiff.m, @chebfun/fracInt.m, @chebtech/chebtech.m, @chebtech/fracInt.m, @fun/fun.m, @onefun/onefun.m, @singfun/fracInt.m, @singfun/singfun.m, @trigtech/fracInt.m, @trigtech/trigtech.m, @unbndfun/fracInt.m, cheb2jac.m, cheb2leg.m, jac2cheb.m, leg2cheb.m, tests/chebfun/test_fracInt.m
Add support for fractional integrals and derivatives of **smooth** `chebfun` objects.
The key idea is to express the function as a Legendre series and then use explicit expressions for the fractional integrals of these guys from §18.17 on NIST.
For half-integrals and derivatives, this is very fast as we need only `cheb2leg()`. For arbitrary values of `mu` it's a little slower as we must convert Jacobi coefficients back to Chebyshev coefficients. This is currently done in `jac2cheb()` using an O(n^2) direct approach (i.e., using the standard recurrence relation). However, since here `mu` is in (0,1), it should be no problem to use the H-T asymptotic approach that is used in `leg2cheb`.
When it comes to adding support for piecewise smooth functions, this approach can be used to compute the …
=> Feature fraccalc new

@chebDiscretization/testConvergence.m, @chebtech/plateauCheck.m, @linop/eigs.m, @linop/linsolve.m, tests/chebtech/test_happinessCheck.m
`plateauCheck` was not respecting `vscales` in array-valued construction properly.
The test which should have caught this (`chebtech/test_happinessCheck.m` test 9) wasn't doing so as the preference to use `@plateauCheck` wasn't being set correctly.
This pull request fixes this, as well as the issues resulting from the change in `chebop` and `linop` classes (which are the main clients of `plateauCheck` and were, for some reason, using column vectors for `vscales`).
=> Fix plateauCheck.

cheb2leg.m
Use `chebfun.dct()` etc for computing DCTs in `leg2cheb()` and `cheb2leg()`.
I haven't yet figured out how to do the DST-1 transpose required by `cheb2leg()` yet. Probably @ajt60gaibb knows how..
=> fix-cheb2leg

@chebfun/dct.m, @chebfun/dst.m, @chebtech1/coeffs2vals.m, @chebtech1/vals2coeffs.m
Ensure real (imaginary) output for real (imaginary) input in DCT and DST
Closes #1380.
(This actually required very little effort, as kinds II-VIII are essentially implemented via kind I in both cases.)
=> fix-dct-real

@chebfun/dct.m, @chebfun/dst.m, @chebfun/idst.m, @chebtech1/coeffs2vals.m, @chebtech1/vals2coeffs.m, @chebtech2/coeffs2vals.m, ultrapoly.m
This is branched off of `fix-dct-real`.
The images below demonstrate the speed up relative to the DST-III (which was unchanged here):
Old:
New:
I don't understand why the higher-number DCTs have gotten worse, however..
Edit: Actually, DCT-III was changed - it got *faster*. This is why DCT-V--VIII appear to have gotten worse.
=> Feature speed up DSTs

@blockFunction/blockFunction.m, @chebfun/chebfun.m, @chebfun/kron.m, @colloc/outer.m, @operatorBlock/operatorBlock.m, tests/chebfun/test_kron.m, tests/chebfun/test_kronOp.m, tests/chebfun/test_mtimes.m
Introducing capabilities for taking the outer product of two CHEBFUNs and getting an OPERATORBLOCK, rather than a CHEBFUN2.
Closes #180 (an issue that's precisely one year old today!) and #1382.
=> Feature outer product operator

@chebfun/gamma.m, @chebfun/nchoosek.m
Two functions that have not yet been implemented in Chebfun.
>> x = cheb.x; f = cos(x); g = exp(x);
>> nchoosek(f,g)
ans =
interval       length   endpoint values  
[      -1,       1]       35       1.1    0.038 
Epslevel = 1.776357e-15.  Vscale = 1.184722e+00.
=> Features GAMMA and NCHOOSEK for chebfuns

@chebop/chebop.m, @chebop/parseBC.m, @chebop/vectorizeOp.m, @cheboppref/cheboppref.m, tests/chebop/test_autoVectorize.m, tests/chebop/test_vectorizeOp.m
Closes #1430.
By default, CHEBOPs will try to vectorize anonymous functions passed to them. It is possible to turn off this feature, either globablly via cheboppref or by setting the ```vectorize``` property of CHEBOPs. This is documented in the help text for CHEBOPs.
=> Feature chebop vectorize

@chebmatrix/chebmatrix.m, @chebop/linearize.m, @functionalBlock/functionalBlock.m, @linBlock/linBlock.m, @linop/linop.m, @operatorBlock/operatorBlock.m, tests/chebmatrix/test_isNotMultOrDiff.m, tests/functionalBlock/test_isNotMultOrDiff.m, tests/operatorBlock/test_isNotMultOrDiff.m
This means that functionalBlock now has this property.
Fixes a crashing chebtest (chebop/test_autoVectorize).
=> Making isMult a property of linBlock, rather than operatorBlock.

@chebfun/disp.m
This addresses #1445. This is what things look now:
```
>> x
x =
interval       length     endpoint values  
[      -1,       1]        2        -1        1 
epslevel = 1.110223e-15   vscale = 1
>> h = heaviside(x)
h =
chebfun column (2 smooth pieces)
interval       length     endpoint values  
[      -1,       0]        1         0        0 
[       0,       1]        1         1        1 
epslevel = 2.220446e-16   vscale = 1   Total length = 2
```
=> some minor display changes.

@chebop/chebop.m, @chebop/disp.m
Closes #1293 and #1443. Some example outputs for displaying ```chebops```:
```
>> N = chebop(@(u) diff(u,2)); N.lbc = 'neumann'; N.rbc = 2
N =
Linear operator:
u |-> diff(u,2)
operating on chebfun objects defined on:
[-1 1]
with
left boundary condition(s):
neumann
right boundary condition(s):
u = 2
```
```
>> N = chebop(@(u) diff(u,2)); N.bc = 'dirichlet'
N =
Linear operator:
u |-> diff(u,2)
operating on chebfun objects defined on:
[-1 1]
with
left boundary condition(s):
dirichlet
right boundary condition(s):
dirichlet
```
```
>> N = chebop(@(x, u, v) [diff(u) - v.^2 ; u - diff(v)], [0 3]); N.lbc = @(u,v) u-2; ...
N.rbc = @(u,v) diff(v) + u
N =
Nonlinear operator:
u,v |-> diff(u)-v.^2
u-diff(v)
operating on chebfun objects defined on:
[0 3]
with
left boundary condition(s):
u-2 = 0
right …
```
=> Fix chebop display

cheb2leg.m, leg2cheb.m, tests/misc/test_cheb2leg.m, tests/misc/test_leg2cheb.m
This is useful in computation of the inverse discrete Legendre transform, which we hope to add soon.
This commit also addresses some small bug fixes left over from the switch in order of coefficients in Chebfun, as well as some general tidying up.
Tests have been added for the new features.
=> Add ability to compute the transpose of the leg2cheb operator.

@chebtech/qr.m, tests/chebtech/test_qr.m
I am excited by this.  It is the first algorithmic speed up of the quasimatrix QR factorization in Chebfun for years.  It is also the first `dlt()` and `idlt()` Chebfun application.  
Let `A` be a `inf x m` quasimatrix with columns of maximum polynomial degree `n`.  The current QR factorization algorithm has a complexity of    `O( n^2m + nm^2 )`.   Using `ndct` and `idlt`, I changed the algorithm slightly so the QR factorization now costs  `O(nm (log n)^2/loglog n + nm^2 )` operations.  This is a big win for tall-skinny quasimatrices. 
For example (do not try this if you are not on this branch!): 
```
A = chebpoly(1e4:1e4+1);        % inf x 2 quasimatrix 
tic, [Q, R] = qr( A ); toc 
Elapsed time is 0.843294 seconds.
```
In `development` this crashes MATLAB as it tries to construct an …
=> Fast tall-skinny QR

@chebgui/demo2chebgui.m, @chebgui/solveGUIeig.m, @chebguiController/loadDemoMenu.m, @chebguiExporterEIG/exportInfo.m, chebguiDemos/eigdemos/advection_diffusion.guifile, chebguiDemos/eigdemos/advection_diffusion_periodic.guifile, chebguiDemos/eigdemos/airy.guifile, chebguiDemos/eigdemos/cross.guifile, chebguiDemos/eigdemos/davies.guifile, chebguiDemos/eigdemos/derivative.guifile, chebguiDemos/eigdemos/double_well.guifile, chebguiDemos/eigdemos/harmonic.guifile, chebguiDemos/eigdemos/harmonic_system.guifile, chebguiDemos/eigdemos/mathieu.guifile, chebguiDemos/eigdemos/orr_sommerfeld.guifile, chebguiDemos/eigdemos/variable_coeffs_system.guifile
Determine properly whether EIG problems are generalized or not.
Solve EIG problems in CHEBGUI in CHEBOP mode, rather than LINOP mode.
Cleaning up exporting code for EIG problems.
This fixes the broken EIG problems of Chebgui.
It also introduces capabilities for automatic testing of EIG demos (via code I haven't pushed yet to the dev-tools repo). This is done through the lines starting with `#` at the top of each `.guifile`, which contain Chebfun code to be executed. I'll issue a separate pull request for the automatic testing of BVPs, IVPs and PDEs.
=> Fix chebgui eig2

@chebmatrix/chebmatrix.m, @chebmatrix/mergeDomains.m, @domain/merge.m
At the moment, there's a lot of inefficiencies in how we deal with checking and merging of domains in `chebmatrix`. Take for example this script brought to my attention by @trefethen , it solves an ODE with a right hand side with a lot of pieces:
```
tic
dom = [0 16];
x = chebfun('x',dom);
f = (x-floor(x))<sqrt(2)/7;
L = chebop(dom);
L.lbc = 0; L.rbc = 1;
L.op = @(x,u) diff(u,2);
tic, u = L\f;
toc
```
On development, I get a running time of 12.93 seconds. On this branch, I get 4.50 seconds.
The main changes it does are as follows:
* Rather than repeatedly calling `domain.merge` as we loop through blocks of a `chebmatrix` in `chebmatrix.mergeDomains`, it starts by building a cell with all the domains, then calls `domain.merge` once.
* It also does more clever checking in …
=> Fix chebmatrix domain checking

@chebfun/cumsum.m, @trigtech/cumsum.m, tests/chebfun/test_cumsum.m
Fixed bug where cumsum of an even trigfun (and trigtech) was not working properly.
Added tests in chebfun/cumsum for cumsums of trigfuns (nothing was there previously).
Partially address #1460.
=> Fix cumsum of an even trigfun (and trigtech)

@chebfun2/isequal.m, tests/chebfun2/test_isequal.m
We need to get the data from g here, not f, whose data we've already extracted.  Also added a test for this method.
This closes #1276.
=> Fix trivial bug in chebfun2.isequal().

@chebfun2v/roots.m, tests/chebfun2v/test_roots01.m
These should be the other way around:  the leading-order coefficient should be the "B" argument, while the constant term should stand in for "A".  This closes #1505 and is the right resolution for #1232.  `chebfun2v.roots` now handles bivariate linear problems correctly.
This commit also reverts the changes made in 8bcf6c4d and 6bb4be81 to address #1232, as the cutoff tolerance is not the issue here.  The reason that making that tolerance smaller appeared to fix things is that it sometimes caused a small leading-order coefficient that in principle _should_ be stripped to not be stripped, so that when the coefficients were passed to `chebT1rtsmatgep` later, the input would have size at least 3 in the third dimension.  This caused the handler for the general case, which does things …
=> Fix reversed arguments to eig() call in chebT1rtsmatgep() in chebfun2v.roots().

@chebfun2/plotcoeffs2.m
Closes #1332.
Er, whoever reviews this should make sure the "rows"/"columns" designation in the labels is correct. I may have mixed them up.
=> Adding axis labels to plotcoeffs2

@chebfun/chebfun.m
Closes #1372.
Note that information on the the new `'doublelength'` flag has already been introduced.
=> Adding documentation for CHEBFUN(F, N).

@chebfun/chebfun.m
Allowing the use of both 'exps' and 'exponents' when constructing a singular function in chebfun level. This is to resolve #1469.
=> Allowing the use of both 'exps' and 'exponents' 

@chebfun/chebfun.m, @chebfunpref/chebfunpref.m, @smoothfun/smoothfun.m, tests/chebpref/test_chebfunpref.m
This set of changes has `chebfunpref` now get the tech preferences "on-demand" whenever they are needed.  As a result, techs can now determine their own default values for the "abstract" preferences that they are required to expose to the upper layers.
I've always felt that this was more or less the right thing to do and only did things the other way for convenience and to avoid the potential performance hit associated with needing to merge tech preferences a little more often.  Crude "profiling" using `chebtest` doesn't show any detectable performance impact on my machine (specifically, `chebtest('chebfun')` takes somewhere between 235s-240s on my machine with and without these changes), so I guess we're OK.
The motivation for making these changes is given in the discussion in #1336, …
=> fix-chebfunpref-techs-determine-defaults

@chebfun/chebfun.m, @chebfun/get.m, chebtest.m
After adding a warning in `chebfun.get`, when I then run chebtest, I get a lot of warnings! This is because in a lot of places, the chebtests still include lines such as
```
tol = 10*get(f, 'epslevel')*get(f, 'hscale');
```
and
```
pass(im+1,k) = norm(feval(f,xx) - F(xx), inf) < 1e2*max(f.epslevel.*f.vscale);
```
which were kept because we wanted to keep the option open to easily reintroduce epslevels.
Since removing those lines would make the reintroduction of epslevels a lot trickier (even though it's unlikely we want to do so), I didn't want to change the tests, instead, I turned off the warning inside chebtest.
Closes #1513.
=> Warning for f.epslevel and get(f,'epslevel').

tests/treeVar/test_toFirstOrder.m
For some reasons, 2015a needs ever so slightly looser tolerance for this test than previous versions.
=> Loosening tolerance for test to pass on 2015a.

@chebfun/pdeSolve.m
Minor fix for `pdeSolve()`.
(The issue is that R2015b is a bit more fussy about assigning structs than previous versions.)
=> Fix for PDESOLVE on R2015b

@chebfun2/constructor.m
These lines in the `chebfun2` constructor seemed odd:
```
colData.vscale = dom(3:4);
tech = pref.tech();
colChebtech = tech.make(sum(colValues,2), colData);
```
I think they're trying to accound for scale invariance in the domain. I changed it to 
```
colData.hscale = norm(dom(3:4), inf);
```
which I think is right. 
All the tests pass either way.
=> Pass hscale information to tech constructors in chebfun2 constructor.

@chebtech/qr.m
Looking at #1542 made me notice this.
Before this fix:
```
>> tic, for k = 1:100, qr(chebtech2(rand(1000,20))); end, toc
Elapsed time is 2.551894 seconds.
```
After:
```
>> tic, for k = 1:100, qr(chebtech2(rand(1000,20))); end, toc
Elapsed time is 0.868198 seconds.
```
Explanation: We cache the matrix which converts Chebyshev values to Legendre values. This is useful if we are doing many transforms of the same length (which is typical in many `chebfun2` commands).
We could remove the problem of checking for type if we _always_ used cheb1 or cheb2 points locally in `qr`. However, this pull request doesn't address this (and it's actually closely related to #1542)
=> Fix caching in chebtech/qr().

@trigtech/sum.m
There is no need to use the trapezium rule in `trigtech/sum`, requiring `O(n)` operations, when the zeroth Fourier coefficient is already known.   The algorithm is now `O(1)` operations.  (This speed up can be seen with very high rank periodic `chebfun2` objects.)
=> Simplify trigtech/sum. 

@chebtech/chebtech.m, @chebtech/happinessCheck.m, @chebtech/sampleTest.m, @chebtech/techPref.m, @singfun/constructSmoothPart.m, @trigtech/techPref.m, tests/bndfun/test_constructor.m, tests/chebfun/test_diff.m, tests/chebfun/test_feval.m, tests/chebfun/test_join.m, tests/chebfun/test_mean.m, tests/chebfun/test_rdivide.m, tests/chebfun/test_splitting_abs.m, tests/chebfun/test_sum.m, tests/classicfun/test_plus.m, tests/classicfun/test_times.m, tests/unbndfun/test_sum.m
To do so, a new field `sampleTestEps` is added to techPref@chebtech and techPref@trigtech. All tests passed.
=> Loosening the tolerance used for sampleTest for the construction of `smoothPart` of singfun. 

@chebfun/chebfun.m, @chebfun/compose.m, @chebtech/chebtech.m, @chebtech/constructorTurbo.m, @chebtech/techPref.m, @chebtech1/chebtech1.m, @chebtech2/chebtech2.m, tests/chebfun/test_constructor_turbo.m, tests/chebtech/test_turbo.m, tests/trigtech/test_qr.m, tests/trigtech/test_restrict.m, tests/trigtech/test_roots.m, tests/trigtech/test_sign.m, tests/trigtech/test_simplify.m
This branch contains a very basic (and very experimental) version of the `turbo` feature that was discussed a few meetings ago.  Some syntax- and sanity-check tests have been included.  This code is far from perfect, but it might be good to get it integrated before ICIAM so that @trefethen can use it for his talk.
I am _not_ proposing at this time that we formally announce the existence of this feature at the next release, as there are still many things to think about regarding it.  For this reason, I have not added documentation to the `chebfun` classdef file acknowledging this feature's existence or telling how to use it.
=> feature-turbo

@trigtech/simplify.m, tests/trigtech/test_simplify.m
Even length `trigtechs` are not being simplified correctly.  For example:
```
>>f = trigtech(ones(8,1));
>> simplify(f)
ans = 
trigtech with properties:
values: 0
coeffs: 0
vscale: 1
hscale: 1
ishappy: 1
epslevel: 2.2204e-16
isReal: 1
```
This pull request fixes the issue, which turned out to be a mistake in the index for the non-symmetric mode.  This is a pretty trivial pull request (only one line and a new test).
=> Fix simplification of an even length trigtech

@separableApprox/waterfall.m
With a default `LineWidth` of 2, a default `MarkerSize` of 7 makes the markers too small to be visible on my machine.
A change of this sort was originally effected in 33854a3e, but this change was probably undone when `separableApprox` got merged into development and replaced `chebfun2.waterfall()` with
`separableApprox.waterfall()`.
=> Set default MarkerSize to 20 in separableApprox.waterfall().

@trigtech/horner.m, tests/trigtech/test_feval.m
Fixes a bug introduced in #1540 where the evaluation of a constant `trigtech` only returns one value regardless of the number of input evaluation points.  A new test has been included for this case.
=> Hot fix for the evaluation of a constant trigtech

@treeVar/toFirstOrder.m, @treeVar/tree2infix.m, @treeVar/treeVar.m
Another PR, which like #1341 was inspired by an example by @trefethen . By avoiding calls to `chebfun/subsref` in output from the `treeVar` class, nice speedups can be obtained. Take for example:
```
L = chebop(0,8); L.lbc = 0;
L.op = @(t,y) diff(y) + y;
t = chebfun('t',[0 8]);
% Smooth RHS
g = sin(t.^2); 
tic, 
for i =1:5
y1 = L\g;
end
time = toc; fprintf('smooth: %4.3fs.\n', time)
% Piecewise RHS
g = sign(sin(t.^2));
tic
for i=1:5
y2 = L\g;
end
time = toc; fprintf('piecewise: %4.2fs.\n', time)
```
On current release branch, I get the timings on my laptop on Matlab 2014b:
```
smooth: 3.482s.
piecewise: 27.03s.
```
On this branch, I get:
```
smooth: 2.515s.
piecewise: 20.27s.
```
On the 2015b prerelease, the timing results are also pretty nice (notice how much faster 2015b appears to be …
=> Eliminate calls to chebfun/subsref in treeVar/tree2infix output.

@chebfun/feval.m, @chebfun/idlt.m
(This PR replaces #1603 )
* Call numColumns instead of size in columnFeval.
* Deal with row chebfuns in feval, rather than columnFeval.
This closes #1600. I didn't do a profiling on the whole of chebtest, but for and chebtest('chebfun'), it turns out that it saved more than 13000 calls to chebfun/size.
Also, for the example listed in #1599, these are the times I get on 2015b prerelease before and after these changes.
Before:
smooth: 0.820s.
piecewise: 5.62s.
After:
smooth: 0.716s.
piecewise: 4.93s.
=> Simplification of code in chebfun/feval

@chebop/determineDiscretization.m, @chebop/eigs.m, @chebop/expm.m, @chebop/solvebvp.m, tests/chebop/test_determineDiscretization.m
Thank you @aaustin141. 
1. Minor modifications in `solvebvp`.
3. `determineDiscretization` now also checks if the rhs of the ODE is discontinuous. If that's the case, `solvebvp` uses Chebyshev-based discretizations, as opposed to Fourier-based ones. 
3. Add tests in `test_determineDiscretization`.
4. Modify `eigs`, `expm` and `solvebvp` to use the new syntax of `determineDiscretization`.
=> Fix a failure in the ode-linear/ContourExpm example, and minor modifications in solvebvp

@chebfun/pdeSolve.m, @chebmatrix/pde23t.m, tests/misc/test_pde15s.m
Also add systems (i.e., `chebmatrix`) support for `pde23t()`.
All demos work, as does the extended `test/misc/test_pde15s()`.
PS. `pdeSolve()` wastes a lot of time building a `chebfun` after each successful time chunk. It might speed things up to simply store values/coefficients as we go a long, and do the `chebfun` construction at the end.
=> Use standardCheck() in PDE15S() and PDE23T().

@trigtech/plotcoeffs.m, tests/chebfun/test_plotcoeffs.m
This is needed to fix crashes in Ch. 11 of the Guide and the example fourier/FourierCoefficients.m which appeared following the merge of #1584.
=> Fix dimension mismatch bug in plotcoeffs(f, 'loglog') for trigtech.

@chebfun/pde15s.m, @chebfun/pdeSolve.m, pdeset.m
If pde15s is called without any outputs, intermediate solutions still
get plotted by default. This is similar to the default behaviour of the
MATLAB ODE solvers, which plot the marching through time if they're called
without outputs. This change is inspired by a discussion with @trefethen
and the use of pde15s in the upcoming book.
=> Turn off default plotting if pde15s is called with outputs.

@chebop/feval.m, tests/chebop/test_cellOperator.m
This allows construction of operators such as
```matlab
function foo
N = chebop(@(r,u) odefun(r,u), [-1 1]);
N.lbc = @(u) [u{1} - 1 ; u{2}];
N.rbc = @(u) [u{1} ; u{2} - 1];
N.numVars = 2; % <-- Why is this is required here?
x = chebfun('x');
u = N\0
plot(u), shg
function op = odefun(r, u)
for n = 1:2
op{n} = diff(u{n}, 2) + n*u{n};
end
end
end
```
=> Fix chebop/feval to vertcat outputs which would otherwise return cell arrays

@chebcolloc/diff.m, @linop/deriveContinuity.m
These are the next steps to addressing the slow piecewise BVP first encountered in #1485:
```
tic
dom = [0 16];
x = chebfun('x',dom);
f = (x-floor(x))<sqrt(2)/7;
L = chebop(dom);
L.lbc = 0; L.rbc = 1;
L.op = @(x,u) diff(u,2);
tic, u = L\f;
toc
```
Before #1485 got merged, this took 12.93 seconds on my computer on development, and the merge brought it down to 4.5 seconds.
The code now takes at around 3.8 seconds on my laptop on development, but on this branch, it's down to 1.3 seconds. This is achieved by constructing the pieces of piecewise operators in a way that saves a lot of Matlab overhead, as can be seen by comparing the two profiler results before and after.
On development:
On branch
The most expensive operation now is blkdiag, which indicates that further improvements might be …
=> Save a lot of overheads when constructing piecewise operators

@chebtech/diff.m, tests/chebtech/test_diff.m
This is necessary because if the degree is low (2, 3), we'll end up calling cumsum() on a row vector, and when operating on a vector MATLAB cumsum() goes along the non-singleton dimension.  That's not desirable in this case:  we always want to cumsum down _columns_ here, even if the vector is a row.
A test has been added to check for this issue.
This closes #1641.
=> Pass dimension to cumsum() in computeDerCoeffs() in chebtech.diff().

@chebfun/deriv.m, tests/chebfun/test_deriv.m
Better syntax for evaluating derivatives of chebfuns. Examples:
```
Example:
u = chebfun(@sin);
deriv(u, 1) % u'(1)
deriv(u, .5, 2) % u''(.5)
deriv(u, 0.1:0.01:0.2) % u'(0.1:0.01:0.2)
```
Closes #1624. See also #1626 for a related issue.
=> Feature chebfun deriv

@chebop/quiver.m
While working on an example for `chebop/quiver`, I realised this would make the plots look much nicer, would be great if someone could quickly merge this minor fix (two lines of code).
=> Set x and y lims in chebop/quiver, make plots much nicer.

@linop/linsolve.m
I don't have a minimal example for this, but the following was sent to me by a user and it works with the fix. All test pass with the change.
```
% Define the parameters
dom = [0 1];                % interval of the space domain.
Nr = 200; Nb = 100;         % number of particles
epr = 0.01; epb = 0.01;     % diameter of the particles
epbr = (epr+epb)/2; 
Dr = 1; Db = 2;             % diffusivities
d = 2;                      % problem dimension (d = 2 or 3)
Vr = @(x) x; Vb = @(x) 2*x; % take potentials that depend on x only
tVr = @(x) Vr(x)/Dr; tVb = @(x) Vb(x)/Db; % rescaled forces with the diffusion
alpha = 2*(d-1)*pi/d;
% Discretise in space:
x = chebfun('x', dom);
% Initial guess
ct = Nr/sum(exp(-tVr(x))); cr0 = log(ct); r0 = ct*exp(-tVr(x));
ct = Nb/sum(exp(-tVb(x))); cb0 = log(ct); …
```
=> Ensure projection matrix has correct dimension when matrices are factored in parametrised problems.

@chebfun2/explain.m
See commit message for details.
@asgeirbirkis, I've assigned this to you, since you were the one who moved `explain()` (formerly `movie()`) into v5.  While we're at it, can we also remove the call to `home` [here](https://github.com/chebfun/chebfun/blob/a0b092892a7ffee20660115cb33d69ba9033a8c7/%40chebfun2/explain.m#L26) and [these lines](https://github.com/chebfun/chebfun/blob/a0b092892a7ffee20660115cb33d69ba9033a8c7/%40chebfun2/explain.m#L202-L206), since they don't seem to serve any purpose anymore?
=> fix-chebfun2-explain

standardChop.m
This PR changes the base index in the plateau computation loop in `standardChop`.
=> changed base loop index from 1 to 2 in standardChop

@chebtech/simplify.m
This fixes a bug in `chebtech/simplify` regarding noisy output coefficients.
=> changed chebtech/simplify to use original coefficients

@trigtech/plotcoeffs.m
Fixed bug where the x-axis properties were not being respected when the plot had been held.
=> Respect x-axis limits with "hold on" in trigtech/plotcoeffs

@adchebfun/adchebfun.m, tests/chebop/test_jump_scaled.m
The code was mostly there, the only thing that needed fixing was to allow passing varargin to `adchebfun/feval` (like we have been able to do for a long time for the standard `chebfun/feval`), so that the correct `functionalBlocks` would be constructed.
Closes #1694.
=> Allow scaled jumps.

@chebfun/deriv.m, tests/chebfun/test_deriv.m
Allow left- and right-sided evaluation in `deriv()`.
Closes #1703.
=> fix-deriv-sided

@chebfun2v/roots.m
`nargchk()`-->`narginchk()` to avoid to following warnings:
```
>> cd tests/chebfun2v
>> test_roots01
Warning: NARGCHK will be removed in a future release. Use NARGINCHK or NARGOUTCHK instead. 
> In chebfun2v/roots>intersections (line 1153)
In chebfun2v/roots>roots_marchingSquares (line 973)
In chebfun2v/roots (line 67)
In test_roots01 (line 14) 
```
=> NARGCHK() is deprecated in R2016a.

@singfun/plus.m
Closes #1423.
We now get:
```
>> cheb.x;
>> sqrt(x) + 0*x
ans =
chebfun column (2 smooth pieces)
interval       length     endpoint values   endpoint exponents
[      -1,       0]        1    complex values         [0      0.5]  
[       0,       1]        1         0        1         [0.5      0]  
vertical scale =   1    Total length = 2
```
=> Treat addition of zero functions as a special case to avoid warnings in singfun/plus.

@singfun/plus.m, tests/singfun/test_plus.m
This partially reverts f337559b.  One of the changes in that commit
removed the lines that pass the vscale information down to the smoothfun
constructor when we hit the case in which the exponents differ by
non-integer values in singfun.plus().  This was causing the example
cheb/Convergence.m to hang because one of the functions it constructs (a
rare instance of a case that actually hits this code and an even rarer
example of one where the construction succeeds) is built by subtracting
two functions that are very close, and the constructor was failing due
to the resulting noise.
=> Pass vscale to smoothfun constructor in singfun.plus().

jacpts.m, tests/misc/test_jacpts.m
Compute the constant out the front in a more stable way using the ratio of gamma functions. See #1707.
=> Fix jacpts

@chebfun/plot.m
Closes #1741.
(Whilst looking at this, it's not clear to me what the colour rules are when plotting delta functions.)
=> Reset color order to original (not to 1) in CHEBFUN/PLOT

@chebop/dampingErrorBased.m, @chebop/solvebvpNonlinear.m, @linop/linsolve.m
If when solving the linear system for the Newton update did not converge, we end up with a gibberish update, from which there is little chance to converge afterward. This will cause the solution process to halt (we're solving something that's way too noisy, with a large discretization size), so it's better to bail out of the Newton iteration. This PR allows the Newton algorithm to exit more gracefully out of such situations.
=> More graceful bailing out of Newton iteration when linear solves go awry

jacpts.m
Use constant for the weights when `n` is small according to @nickhale's suggestion in #1707.
=> fix constant for the weights in 'jacpts'

tests/misc/test_ultrapts.m, ultrapts.m
ULTRAPTS() command for ```-1/2 < lambda < 30```. Compute the nodes and weights for Gauss-Gegenbauer quadrature in a region never been used on Chebfun. The algorithm is computed in O(n) operations to an accuracy of double precision. Also, the algorithm can return the barycentric weights and the arccos of the nodes. Furthermore, in the same range, ```ultrapts``` is much faster than ```jacpts```. If ```0 < lambda < 1```, then the convergence of Newton-Raphson is guaranteed with selected initial guesses.
=> Update ultrapts.m for -1/2<lambda<30

@ultraS/convertmat.m
See comments on #1729 and #1509.  This is documentation that occurs in a part of the system that I don't completely understand, so I'm issuing a pull request for it.  It might actually be a better idea to tweak `ultraS.convertmat()` to do what its help text originally said, as that interface would be less confusing.
=> Fix help text for ultraS.convertmat().

@chebfun2/disp.m
This does what it says on the tin: removes that pesky expression "1 smooth surface" from every display of a chebfun2.   (This is my first pull request!)
=> removed "(1 smooth surface)" from @chebfun2/disp.m

@chebfun/chebfun.m, @chebfun/resetPointValues.m, @chebfun/roots.m, @chebfun2/constructor.m, @chebop2/solvepde.m, @separableApprox/simplify.m, tests/chebfun2/test_constructor2.m, tests/chebfun2/test_ctorsyntax.m
Major overhaul of `chebfun2` constructor input parsing. All the tests pass (remarkably..)
As a consequence we can now do this (see #1764).
```
>> chebfun2(@(x,y) 1./(1+25*(x.^2+y.^2)))
ans =
chebfun2 object (1 smooth surface)
domain                 rank       corner values
[  -1,   1] x [  -1,   1]       19     [0.02 0.02 0.02 0.02]
vertical scale =   1 
>> chebfun2(@(x,y) 1./(1+25*(x.^2+y.^2)), 'eps', 1e-8)
ans =
chebfun2 object (1 smooth surface)
domain                 rank       corner values
[  -1,   1] x [  -1,   1]        9     [0.02 0.02 0.02 0.02]
vertical scale =   1 
```
=> Major overhaul of input parsing in chebfun2.

@chebfun2v/dot.m
The `chebfun2v/dot` command now respects the underlying tech.  
Now we have
```
chebfunpref.setDefaults('tech',@trigtech)
x = chebfun2(@(u,v) (3+cos(v)).*cos(u), [-pi pi -pi pi]);
y = chebfun2(@(u,v) (3+cos(v)).*sin(u), [-pi pi -pi pi]);
z = chebfun2(@(u,v) sin(v), [-pi pi -pi pi]);
S = [x; y; z];
E           =   dot(S,S);
[C,D,R] = cdr( E ) 
C =
interval       length     endpoint values  trig
[    -3.1,     3.1]       10     -0.15    -0.15 
vertical scale = 0.59 
D =
68.252862777426245
R =
interval       length     endpoint values  trig
[    -3.1,     3.1]        4      -0.4     -0.4 
vertical scale = 0.4 
```
showing that periodic output was calculated from periodic input.
=> Fix chebfun2v/dot: Respect underlying tech

@chebtech/innerProduct.m, @trigtech/innerProduct.m
This pull request allows one to take inner-products between `chebtechs` and `trigtechs` by doing the appropriate conversions at the tech level. See issue #1784.
=> modified trigtech and chebtech innerProducts to handle mixed tech cases

@chebfun/innerProduct.m, @chebtech/innerProduct.m, @trigtech/innerProduct.m, tests/chebfun/test_innerProduct.m
This is a re-do of #1787 that moves the tech type-casting in `innerProdcut()` to `chebfun`, where it belongs, instead of `chebtech` and `trigtech`.  We do all other casting for binary operations with mixed tech types in `chebfun`, so this should be done there as well.  Also adds some tests.
=> fix-mixed-tech-innerProduct

@chebmatrix/chebmatrix.m, @linop/eigs.m, tests/linop/test_eigsRayleigh.m
This pull request allows one to improve the accuracy of the computed eigenpairs in `linop/eigs` by doing one step of inverse (Rayleigh) quotient iteration. This feature is enabled by passing a flag in the call to `eigs`. This feature is only implemented at the `linop` level since I don't think the average user will need to deal with this. This PR depends on #1787.
=> Higher accuracy eigenvalues in eigs

tests/linop/test_eigsRayleigh.m
There was some missing text in a test in #1788 that is fixed by this commit.
=> fixed typo in tests/linop/test_eigsRayleigh

@trigtech/coeffs2vals.m, @trigtech/refine.m, @trigtech/vals2coeffs.m, tests/trigtech/test_coeffs2vals.m, tests/trigtech/test_roots.m, tests/trigtech/test_vals2coeffs.m, trigpts.m
This pull request enforces symmetry in `tripts`, `trigtech/vals2coeffs` and `trigtech/coeffs2vals`. See #1814.
=> Fix trigpts symmetry

@chebtech1/coeffs2vals.m, @chebtech1/vals2coeffs.m, @chebtech2/coeffs2vals.m, @chebtech2/vals2coeffs.m, tests/chebtech1/test_coeffs2vals.m, tests/chebtech1/test_vals2coeffs.m, tests/chebtech2/test_coeffs2vals.m, tests/chebtech2/test_vals2coeffs.m
This pull request enforces symmetry that is lost using Matlab's `fft` in `chebtech1` and `chebtech2`. See #1814.
=> added symmetry reinforcement to chebtech1 and chebtech2

@separableApprox/roots.m, tests/chebfun2/test_roots.m
The following was failing: 
```
f = chebfun2( @(x,y) 1/2-y);
r = roots( f );
```
because of an internal bug when `f` is of rank 1.  Fixed now.
=> Fix chebfun2 roots

@spherefun/constructor.m, @spherefun/poisson.m, tests/spherefun/test_Poisson.m, tests/spherefun/test_composition_operators.m, tests/spherefun/test_constructor.m, tests/spherefun/test_sphharm.m
The solution to Poisson's equation laplacian(u)=f on the sphere only makes sense when f has a mean of zero on the sphere.  This is the compatibility condition for Poisson's equation.  
This PR modifies `spherefun.poisson` to deal with the case where f does not have mean zero.  A warning is now issued and the mean of f is subtracted from f before solving.
Once this PR is merged, Chapter 17 of the guide will need to be updated with the new syntax for calling `spherefun.poisson`.
=> Fix spherefun poisson when right hand side does not have a mean of zero

@spherefun/constructor.m, tests/spherefun/test_constructor.m
Fix this (coming from `g.cols` not being `trigtech` objects): 
```
f = spherefun(@(x,y,z) cos(x));
g = spherefun(f,0)
g =
No appropriate method, property, or field 'isReal' for class
'chebtech2'.
Error in chebfun/subsref (line 150)
out = subsref(out, index);
Error in spherefun/sample (line 59)
if ( all(cols.funs{:}.onefun.isReal) &&
all(rows.funs{:}.onefun.isReal) )
Error in separableApprox/vscale (line 27)
vals = sample(f, m, n);
Error in spherefun/vscale (line 10)
[varargout{1:nargout}] = vscale@separableApprox(varargin{:});
Error in spherefun/disp (line 23)
vscl = vscale(F);                         % vertical scale
Error in spherefun/display (line 18)
disp(X); 
>> edit spherefun/constructor.m
```
=> The cols and rows need to be trigtechs for a spherefun object.

@spherefun/roots.m
```
>> test_roots
Undefined function or variable 'cellmat'.
Error in spherefun/roots (line 32)
r = cellmat(size(vals,2), 1);
Error in test_roots (line 14)
r = roots(f); 
```
Presumably `cellmat()` is from some toolbox that I don't have?
Anyway, it only needed a cell.
=> Fix spherefun roots

@separableApprox/feval.m
This pull request improves the speed of `separableApprox/feval` in the case that the input arguments are matrices.  Here's a demonstration of the speed up for `spherefun` objects:
```
>> g = spherefun(@(lam,th) cos(10*cos(lam-0.2).*sin(th)+2*cos(th).^2));
>> ll = rand(100,100);  tt = rand(100,100);
>> tic, h = g(ll,tt); toc  % On development
Elapsed time is 4.683748 seconds.
>> tic, h = g(ll,tt); toc  % On branch speedup-separableApprox-feval
Elapsed time is 0.148328 seconds.
```
=> Speed up separableApprox/feval

+cheb/x.m, +cheb/xy.m, +cheb/xyzsphere.m
This pull request implements the commands `cheb.xy` and `cheb.xyzsphere`. 
```
cheb.xy 
x =
chebfun2 object
domain                 rank       corner values
[  -1,   1] x [  -1,   1]        1     [  -1    1   -1    1]
vertical scale =   1 
y =
chebfun2 object
domain                 rank       corner values
[  -1,   1] x [  -1,   1]        1     [  -1   -1    1    1]
vertical scale =   1 
```
Note that `cheb.x` has changed from
```
cheb.x
ans =
interval       length     endpoint values  
[      -1,       1]        2        -1        1 
vertical scale =   1 
```
to (see variable name `x`)
```
cheb.x
x =
interval       length     endpoint values  
[      -1,       1]        2        -1        1 
vertical scale =   1 
```
Closes …
=> Add cheb.xy and cheb.xyzsphere shortcut commands

@chebfun2/sample.m, @spherefun/sample.m
This PR includes the following:
First, `chebfun2/sample` now calls the `sample` function of the techs that makes up the the rows and columns instead of always sampling on a tensor product Chebyshev grid.  This dramatically improves the speed of some operations.  Here's an example where two Chebfun2 objects are constructed with the `trig` flag:
```
>> f = chebfun2(@(x,y) tanh(10*(1+cos(5*pi*(x-0.2)).*sin(7*pi*y))),'trig');
>> g = chebfun2(@(x,y) cos(20*pi*cos(pi*x).*sin(pi*y)),'trig');
```
Adding these together and displaying the result on the development branch takes the following amount of time:
```
>> tic, h = f+g, toc 
h =
chebfun2 object
domain                 rank       corner values
[  -1,   1] x [  -1,   1]       62     [   2    2    2    2]
vertical scale =   2 
Elapsed time is …
```
=> Fix chebfun2 and spherefun sample method

@spherefun/sphharm.m
This PR speeds `sphharm` up by a factor of about 2.  It also fixes a bug associated with constructing some of the negative power spherical harmonics.  For example, in development, the construction of the `l=16`, `m=-16` spherical harmonic causes an erroneous warning and improper construction:
```
>> f = spherefun.sphharm(16,-16)
Warning: Unresolved with maximum length: 65537. 
> In spherefun/constructor>PhaseTwo (line 706)
In spherefun/constructor (line 146)
In spherefun (line 48)
In spherefun.sphharm (line 42) 
f =
spherefun object
domain        rank    vertical scale
unit sphere       2          0.063
```
These bugs will be fixed with PR.
=> Improve construction of spherical harmonics

@chebfun3v/integral2.m, tests/chebfun3v/test_integral2.m
Adds an integral2 command to compute the flux of a chebfun3v object through a 2D-surface.
This addresses #1924 .
=> Feature chebfun3v/integral2

@chebfun/chebcoeffs.m, @chebfun/legcoeffs.m, @chebtech/chebcoeffs.m, @chebtech/poly.m, @classicfun/chebcoeffs.m, @spherefun/chebcoeffs2.m
This pull request mainly adjusts help text in `@chebfun/plotcoeffs` in response to questions raised by @klauszuoxinwang.  The old and new help texts are reproduced below.  In addition, a number of spurious appearances of `FOURCOEFFS` in help texts have been changed to `TRIGCOEFFFS`.
Old help text:
```
chebcoeffs   Chebyshev polynomial coefficients of a CHEBFUN.
A = chebcoeffs(F, N) returns the first N Chebyshev coefficients of F is
the column vector A such that F = A(1) T_0(x) +  A(2) T_1(x) + ... + 
A(N) T_(N-1)(x), where T_M(x) denotes the M-th Chebyshev polynomial of the
first kind.
If F has a 'finite' Chebyshev expansion (i.e., it is a smooth CHEBFUN with
no breakpoints or endpoint singularities and is based on a CHEBTECH), then
chebcoeffs(F) is equivalent to chebcoeffs(F, LENGTH(F)). …
```
=> Fix chebcoeffs helptext

lagpts.m, tests/misc/test_lagpts.m
I apologise for merging. It looks like after the last commit, I forgot to run `chebtest`.  Here's the small fix in the barycentric weights that is required.
=> Fix lagpts bary weights when n>250.

@separableApprox/subsref.m, tests/chebfun2/test_subsref.m
In Line 40 of `separableApprox/subsref`, a single input was
unnecessarily assumed to be complex. This is now removed. A test is
also added for this.
=> fix  #1956

@chebfun/max.m, @chebtech/minandmax.m, tests/chebfun/test_max.m, tests/chebfun/test_min.m
Ensure min and max of constant functions are at the centre of the domain. (Consistent with roots.)
On development:
```
>> [y, x] = min(chebfun(0))
y =
0
x =
-1
```
On this branch:
```
>> [y, x] = min(chebfun(0))
y =
0
x =
0
```
=> fix-chebfun-minandmax-again

@chebfun2/eig.m, tests/chebfun2/test_eig.m
Adds chebfun2.eig, which computes the eigenvalues and eigenfunctions of a chebfun2 object. 
If d is an eigenvalue of F with eigenfunction w, then this holds: \int f(x,y)w(x)dx = d w(y). 
The domain needs to be square but the chebfun2 can be nonsymmetric. Uses eig(AB) = eig(BA) as a crucial tool.
=> Feature chebfun2 eig

@spherefun/sampleTest.m
This fixes issue #1966 by allowing the constructor to set a complex-valued function to real values only, as is described in the warning.
=> change sampletest to match how constructor handles complex-valued op

@chebfun/remez.m, tests/chebfun/test_remez.m
This is to fix the nightly failure regarding (C) ATAP/chap24.m. 
The 'fix' on Aug 26 was incorrect for remez(odd functions); it should always be (odd,even) to avoid poles at 0.
=> Fix remez for odd functions

@chebfun/remez.m
Fixes remez for odd functions with input type (0,n). In this case the output is the constant function 0. 
Also loosened tolerance for rational remez to avoid warnings with test_remez; it is still too stringent considering how fragile rational-remez is.
=> Fix remez(oddfunction,0,n)

@chebfun/constructODEsol.m, @chebop/chebop.m, @chebop/disp.m, @chebop/solveivp.m, @cheboppref/cheboppref.m, tests/chebop/test_maxnorm.m
Allow the IVP solver to bail out if the norm of the solution grows too big. Closes #1964 . Replaces `feature-cheboppref-maxnorm`, as it's better designed to attach this information to the `chebop`, rather than `cheboppref`, also, it avoids having to introduce a global option for easily specifying it.
This works for scalar problems and systems. Also, supports piecewise problems.
Examples (from the test file included):
Scalar problem:
```
T = 30 ; N = chebop(0,T); t = chebfun('t',[0,T]); N.maxnorm = 10;
N.op = @(t,y) diff(y,2)+y-0.09*y^3; N.lbc = [-1; 0];
y = N\sin(0.05*t)
y =
chebfun column (2 smooth pieces)
interval       length     endpoint values  
[       0,      29]      155        -1       10 
[      29,      30]        1       NaN      NaN 
vertical scale =  10    Total length = 156 …
```
=> Feature chebop maxnorm

@chebfun/compose.m, tests/chebfun/test_compose_chebfuns.m
On development, if `f` is a 1D `trigtech` and `g` is a chebfun, then `h = g(f)` is not a `trigtech`:
```
f = chebfun(@(x) sin(pi*x), 'trig');
g = chebfun(@(x) x.^2);
h = g(f)
h =
interval       length     endpoint values  
[      -1,       1]       29  -8.2e-17 -8.2e-17 
vertical scale = 0.99
```
On this branch, if `g` is a smooth chebfun (no breakpoints), then `h = g(f)` is again a `trigtech`:
```
h =
interval       length     endpoint values trig
[      -1,       1]        5   5.6e-17  5.6e-17 
vertical scale = 0.9
```
If `g` has breakpoints, then `g(f)` will not be a `trigtech`.  Closes #1963 .
(The same will be true for a periodic Chebfun2, 2v, 3, 3v object `f` after #1962 is merged.)
=> Fix #1963: g(f) is periodic if f is periodic and g is smooth

@chebfun2/coeffs2.m, tests/chebfun2/test_chebcoeffs2.m
The third argument of `coeffs2` (i.e. the requested number of columns in the coefficient matrix) is ignored if the second argument (i.e. the requested number of rows) is greater than the number of rows stored in the `chebfun2`. For example,
```
>> f = chebfun2(@(x,y) x+y);
>> coeffs2(f,1,2) % correct
ans =
0     1
>> coeffs2(f,2,1) % incorrect
ans =
0     1
1     0
```
The bug exists on line 44 of coeffs2.m. `if ( mf <= m )` should be `if ( nf <= n )`.
=> Fix bounds checking on third argument of chebfun2/coeffs2

@separableApprox/surf.m
Fix this:
```
t = chebfun2(@(t,p) t,[0 2*pi -pi/2 pi/2]);
p = chebfun2(@(t,p) p,[0 2*pi -pi/2 pi/2]);
[x,y,z] = sph2cart(t,p,0*t+1);
surf(x,y,z), axis equal
```
(The code should return a surface plot of the sphere.)
=> Fix for chebfun2/surf parametric surfaces

@chebfun2/disp.m
Closes #1915 
This displays “trig” if the chebfun2 object is doubly periodic. For example:
```
>> f = chebfun2(@(x,y) sin(pi*(x+y)), 'trig')
f =
chebfun2 object  (trig)
domain                 rank       corner values
[  -1,   1] x [  -1,   1]        2     [4.2e-16 1.5e-16 1.5e-16 -1.1e-16]
vertical scale = 0.98 
```
=> fix-chebfun2-disp-trig

aaa.m, tests/chebfun/test_aaa.m
If no sample points are given, AAA(F) tries to resolve the function on its
domain by chosing sample points in an automated way.
Also fix bug of empty inputs.  Fix #2022 .
=> Automated choice of sample sets in AAA()

aaa.m
when 'mmax' is provided and the sample set is not.
Fix #2027 .
=> Suppress warning message in aaa()

@separableApprox/plot.m
closes #2017 : When plotting a complex-valued function, the
colormap is set to hsv (phase portraits).  In a subsequent plot of a
real-valued function, the colormap is not changed back to default.
=> Fix colormap issue in separableApprox/plot

@chebfun3/private/singleSignTest.m
Adjusting the tolerance in ```@chebfun3/private/singleSignTest.m```. This makes sure that example approx3/ChangeVar3D passes on ALL machines.
At the moment, on the maths machine, when a certain (positive) jacobian is computed at line 43 in the example approx3/ChangeVar3D the minimum returned is -eps, which causes the singleSignTest to fail on the maths machine and consequently a nightly test also fails.
=> Loosening singleSignTest tolerance in Chebfun3

@chebfun/trigpade.m, tests/chebfun/test_trigpade.m, trigratinterp.m
This branch implements trigonometric Pade approximation of a periodic Chebfun.
Try the following code for fun, which compares the best trigonometric type (2,2) approximation of abs(x) with its type(2,2) trigonometric Pade approximation.
```
LW = 'linewidth';
FS = 'fontsize';
t = chebfun('t');
f = abs(t);
fh = @(t) abs(t);
ft = chebfun(fh, 'trunc', 21, 'trig');
m = 2;
n = 2;
[p, q, ~] = trigpade(ft, m, n);
[p_r, q_r, ~, e] = trigremez(f, m, n);
r_p = p./q;
r_r = p_r./q_r;
subplot(2, 1, 1)
plot(f, 'k', LW, 1.2)
hold on
plot(r_p, 'r', LW, 1.2)
plot(r_r, 'b', LW, 1.2)
legend('|\theta|', 'trigpade(f,2,2)', 'trigremez(f,2,2)')
hold off
grid on
str = '$f(x) = |\theta|$, \verb|trigpade(f,2,2)| and \verb|trigremez(f,2,2)|';
h = title(str, FS, 11);
set(h, 'interpreter', 'latex')
h = …
```
=> Feature trigpade

@separableApprox/roots.m, tests/chebfun2/test_roots.m
I've just changed half a dozen lines in separableApprox/roots to compute an empirical arc length before interpolating to the Chebyshev grid, to handle non-smoothly spaced data.  This seems to improve accuracy of arc length and area coefficients by several digits.  For example (see `tests/chebfun2/test_roots`), the sequence
```
f = chebfun2( @(x,y) x.^2 + y.^2 - 1/4 );
c = roots(f);
arclength = sum(abs(diff(c)));
area = abs(sum(real(c).*diff(imag(c))));
```
used to give 2 digits of accuracy and now it is 5 digits.  A discussion of this mathematics can be found in the Chebfun team dropbox folder as Chebfun2Roots.pdf.
It would be nice if somebody could review this quickly as it's short and kathryn.gillow@maths.ox.ac.uk would like to take advantage of this feature.
=> improve accuracy in Chebfun2/roots

randnfun.m, randnfuntrig.m, tests/misc/test_randnfun.m, tests/misc/test_randnfuntrig.m
With discussion with abdullateef.hajiali@maths.ox.ac.uk, I've added new codes 'randn' and 'randfun' in our root directory.  This are continuous analogues of 'randn', producing smooth random functions (periodic or not) with a specified spatial scale DT and domain.  The underlying mathematical ideas may evolve but I am eager to get some of this material into Chebfun to help our explorations and also to help in researching associated questions of stochastic ODEs driven by smooth data and in writing Chapter 12 of _Exploring ODEs_.
These codes are short and should be easy to review.
Questions:
(1) Is this "rectangular window" of Fourier coefficients right, or would Gaussian be better?  (I am speaking here of the covariance function when 'randnfun' is regarded as generating a sample from a …
=> Feature randnfun

@separableApprox/roots.m, tests/chebfun2/test_roots.m
I've made various improvements to Chebfun2 roots so that in simple cases at least, it gets very good accuracy.  Since @sfilip reviewed the last round of improvements to roots, perhaps he might take a look at this one too?
Here's an example of the arc length of a parabola.  All digits displayed are correct.
```
>> f = chebfun2(@(x,y) y-x.^2);
>> sum(abs(diff(roots(f))))
ans = 2.957885715089195
```
Roots is still not perfect, especially when there are intersecting or near-intersecting curves.
=> Chebfun2 roots again

@chebfun/plot.m
Previously, we just replotted the existing line data and set the plot's
"Visible" property to 'off'.  This doesn't work properly anymore in
R2016b, since MATLAB grays out the legend entries for graphics items
marked invisible.
The fix is easy enough:  we plot NaN data for the dummy plot (but set
the line and point styles appropriately) and leave "Visible" set to
'on'.  MATLAB doesn't draw anything on the plot for NaN data, so we're
good.  A little ugly, but we already use this trick elsewhere for other
things.
Closes #2061.
=> Use NaN data for the dummy plot in chebfun.plot().

@trigtech/horner.m, tests/trigtech/test_feval.m
Small bug in the Horner algorithm for evaluating array-valued, complex trigtechs that are of even length.  Included a test for this rare case.  Here's an example of the bug:
```
f = chebfun(@(t) [exp(pi*1i*t) exp(2*pi*1i*t)],'trig','trunc',4)
f(1/2)
ans =
1.0e+02 *
-0.000000000000000 + 0.010000000000000i  2.677467614837482 - 0.000000000000001i
```
=> Fixes a bug in the evaluation of an even length, array-valued trigtech

aaa.m, tests/chebfun/test_aaa.m
This fixes a bug in the cleanup phase of aaa (invoked to remove spurious pole-root pairs when present).
=> fix aaa cleanup

@trigtech/refine.m, @trigtech/trigtech.m
Fixes the `trigtech` constructor so that it does not include a separate evaluation of the right end point to determine the average value of the function at the left end point.  Now evaluations are done over `[-1,1]` all at once and the value `f(-1)` is redefined to `f(-1) = 0.5*(f(1) + f(-1))`.
=> Fix trigpts end points

randnfun.m, randnfuntrig.m
I've made the input arguments to `randfun` and `randnfuntrig` more flexible.  Now there can be any number of arguments 0, 1, 2, or 3:
```
f = randnfun(dx, n, dom)
```
where `dom` is an interval `[a, b]`.  By default dx = 1, n = 1, and dom = [-1 1].  The arguments can appear in any order except that the first scalar, if any, is taken to be `dx` (the space scale) and the second scalar, if any, is taken to be `n` (the number of columns).
Thus for example, for a plot of a random walk on [0, 100] we used to have to type
```
plot(cumsum(randnfun(1,1,[0 100]))
```
but now we can get away with
```
plot(cumsum(randnfun([0 100])))
=> New randnfun syntax

@chebfun/chebpade.m, tests/chebfun/test_chebpade.m
This small change fixes bug #1992 inside chebpade when specifying the number of terms to use in the Chebyshev expansion of the function to approximate.
=> changing ends to domain

@chebfun/mean.m, tests/chebfun/test_mean.m
Until now, Chebfun lacked the functionality of `mean(f,2)` to compute the mean of a Chebfun quasimatrix in the horizontal direction.  We (@sfilip and I) have now implemented that, along with the appropriate (we hope) capabilities for taking means if `f` happens to be transposed.  
A key motivation here is exploration of random functions.  For example, `f = randnfun(.1,10)` gives a quasimatrix whose 10 columns are independent random functions.  What is the mean of these functions?  We want to be able to compute this with `mean(f,2)`.
=> improved functionality of mean(chebfun)

@chebop/ctranspose.m, tests/chebop/test_adjoint.m
Add `ctranspose` method for CHEBOP class so that `A'` is a wrapper for `adjoint(A)`.
=> feature-transpose-is-adjoint

randnfun.m, randnfuntrig.m, tests/misc/test_randnfun.m, tests/misc/test_randnfuntrig.m
For random ODE (and other) applications involving `randnfun` and `randnfuntrig` we want two possibilities: variance 1 at each point (easy to remember, very simple) or variance 1/dt at each point (so that we approach white noise as dt -> 0).  I've added the option `'norm'` to `randnfun` and `randnfuntrig` to make this possible.
=> modifications to allow normalized random functions

randnfun.m
This speeds up `randnfun` by a factor of about 3 by using an explicit Chebyshev grid rather than adaptive construction.  It does not use the NUFFT, though further speedups may be available through that route.
=> speedups to randnfun.m

@chebfun/parsePlotStyle.m, tests/chebfun/test_plot.m
With the previous code, things like `plot(f, 'JumpLine', {'LineStyle', '--'});` do not work because the regex `'[bgrcmykw]'` matches the `'y'` in `'LineStyle'`, causing it to get converted to `'Color', 'y'`.
We fix this by checking to see if the string being parsed is actually a valid line style before accepting the parsing results.
=> Fix handling of MATLAB line styles for 'JumpLine' in chebfun.parsePlotStyle().

@chebfun/chebfun.m, @chebfun2/constructor.m, @chebfun3/constructor.m, tests/chebfun/test_constructor_equi.m, tests/chebfun/test_mtimes.m, tests/chebfun2/test_constructor2.m, tests/chebfun3/test_constructor2.m
This pull request addresses issue #2052. An appropriate error message is now displayed when a user tries to adaptively construct a chebfun/chebfun2/chebfun3 object from equispaced data.
=> Fix equiflag

randnfun.m, randnfun2.m, randnfundisk.m, randnfunsphere.m
We've had endless confusion in randnfun caused by the parameter dt looking like a differential in an integral.  Accordingly I have renamed it lambda in all the randnfun/2/disk/sphere functions.  This name makes sense since the parameter is equal to a typical wavelength of the functions generated.
=> changed DT to LAMBDA everywhere

jacpts.m
Use beta function rather than ratio of gamma functions in `jacpts`.
Partly addresses #2134.
=> fix-jacpts-beta

minimax.m
This pull request addresses #2145. The previous code was not covering all cases when a CF-based initialization could fail.
=> bug fix for minimax

@chebfun/integral.m
Integral should only accept a subdomain of the given chebfun.
Closes #2149.
=> fix-integral-limits

@spherefun/fastSphereEval.m, @spherefun/rotate.m
Slightly modify the low-rank representation of the internal matrices `Ay` and `Ax` so that the most expensive line can be done in real arithmetic.  This gives us another x2 speed up in `spherefun.rotate`! 
Now, we have 
```
f = randnfunsphere(0.03); 
tic
g = rotate(f, 0.1, 0.1, 0.1); 
toc
Elapsed time is 0.388473 seconds.
```
We never use the `feval` method now, the `nufft` is almost always faster, and usually by orders of magnitude. 
...We need to start finding out what the world-record is... 👍
=> Even faster spherefun rotate

randnfun.m, tests/misc/test_randnfun.m
I've made some modifications to `randnfun` to match the literature of Fourier-Wiener series better, and to make it possible to construct Brownian paths or random ODE solutions that converge to a single path as lambda -> 0.   For example the commands
``` 
s = randi(100);
rng(s), f1 = randnfun(0.5,'norm',[0 10],3);
rng(s), f2 = randnfun(0.1,'norm',[0 10],3);
plot(cumsum(f1),'k',cumsum(f2),'r')
```
give a plot like the one below.
I'm going to merge this myself, because nobody else is around just now and I need to code for my talk at the SIAM Annual Meeting next week.
=> modifications to randnfun

jac2jac.m, tests/misc/test_ultra2ultra.m, ultra2ultra.m
Ultraspherical to ultraspherical conversion.
This is essentially just a wrapper for `jac2jac`, but the scalings can be tricky to compute (particularly for large n) so I think it's worthwhile having such a method. (I had my own version and I've been using it a lot.)
I also fixed two small bugs in `jac2jac` that occur when `n = 1` or `n = 2`.
=> feature-ultra-to-ultra

chebcoeffs2chebvals.m, chebvals2chebcoeffs.m, chebvals2chebvals.m, chebvals2legcoeffs.m, chebvals2legvals.m, hermpts.m, lagpts.m, legcoeffs2chebvals.m, legvals2chebvals.m, tests/misc/test_coeffs2vals.m
Modified vals2coeffs code to work with either first- or second-kind Chebyshev grids.
Added a test for all of these codes (which was totally lacking?).
Add chebvals2chebvals for converting between Chebyshev grids.
=> Feature-vals2coeffs-1stkind

@chebop/solveivp.m, @treeVar/sortConditions.m, @treeVar/toFirstOrder.m, @treeVar/treeVar.m, tests/chebop/test_ivp_chebmatrix_syntax.m, tests/treeVar/test_sortConditions.m, tests/treeVar/test_toFirstOrder.m
Syntax for indexed variables, such as
N.op = @(x,u) [diff(u{1},2) + u{2}; sin(u{1}) + diff(u{2})]
has long been supported for BVPs. This was missing for IVPs, which
this PR aims to rectify.
=> Support for CHEBMATRIX syntax for IVPs.

@treeVar/treeVar.m, tests/chebop/test_firstOrderIntegralEqn.m, tests/chebop/test_intops.m
This is to fix an issue originally raised on the Google group, https://groups.google.com/forum/#!topic/chebfun-users/0dpsggp1RyA .
`treeVar` was missing a `sum` method, which has now been added to work analogous to the `cumsum` method of the `treeVar` class (throw a meaningful error, and try switching automatically to global methods, rather than time-stepping).
=> Fix tree var sum

@chebfun/chebfun.m, tests/chebfun/test_constructor_inputs.m, tests/chebfun/test_constructor_inputs_periodic.m
This was causing the constructor to hang since evaluation with a column of values would return a single row of output values.  Fixes #2209.
=> Enforce that the constructor return a chebfun column when the input is a chebfun row

@chebfun/power.m, tests/chebfun/test_power.m
When raising a chebfun to an array of powers, make sure the result is converted from a quasimatrix to an array-valued chebfun.  Fixes #2211.
=> Bug fix for raising a chebfun to an array of powers

aaa.m, tests/chebfun/test_aaa.m
This pull request offers a quick fix to `aaa` failing when infinite data values are supplied by the user (see issue #2217). Following the suggestion of @trefethen, it simply removes infinite values from F(Z) and the corresponding entries from Z.
=> Fix for aaa failing with infinite data values

minimax.m, tests/misc/test_minimax.m
This pull request adds the following feature: when calling `minimax`, the poles of the best approximation are now computed and stored in the output argument `status.pol`.
=> code for outputting the poles of the best approximation

randnfun.m, tests/misc/test_randnfun.m
Aurya Javeed of Cornell's Center for Applied Math found that `randnfun` had the wrong normalization by a factor of sqrt(2) in `'norm'` mode.  I think I have now fixed this.
=> Fix randnfun normalization

randnfun.m, tests/misc/test_randnfun.m
I've changed the flag `'norm'` (which is confusing -- is it the big version of a random function that we call normalized, or the small one?) -- to `'big'`.  Thus now:
randnfun(lambda):  a function of size O(1)
randnfun(lambda,'big'): a function of size O(1/sqrt(lambda)), suitable for integration for Brownian motion and other stochastic effects
=> norm -> big in randnfun

minimax.m
This pull request fixes issue #2230 . It modifies a hard coded value of the leveled error variable `h` that prevented the code from executing correctly in certain cases.
=> fix buggy initialization of the levelled error

randnfun.m, randnfun2.m, randnfundisk.m, randnfunsphere.m, tests/misc/test_randnfunsphere.m
There was a mistake in how we were relating the truncation level of a random spherical harmonic series to the wave-length of the maximum resolved wave.  The primary purpose of this PR is to fix this mistake.  There was an additional bug where the sampling of the random spherical harmonic series at grid of values was not quite large enough to guarantee that we recovered the highest degree sine mode.  This also fixed with this PR.  Finally, the help text was updated.
=> Fix truncation level in randnspherefun

@chebop/quiver.m, tests/chebop/test_quiver.m
Closes #2238.
For example
```
N = chebop(@(t,u) diff(u)-sin(t)*u);
quiver(N,[-1.2*pi 1.2*pi -1 1])
```
yields the following figure:
I did some spot checks plots currently created using quiver, and they seemed to still give the original results.
=> Feature quiver slopefield

@chebfun/nufft.m, tests/misc/test_nufft.m
Fix bug in `chebfun.nufft` that only showed up in nufft-type-II for highly nonuniform freqs.
=> Fix nufft for highly nonuniform freqs

@chebfun/mtimes.m, @chebfun/rdivide.m, @singfun/cancelExponents.m, @singfun/simplifyExponents.m
I work a lot with weighted Jacobi and Ultraspherical polynomial bases, and it would be useful for me to be able to construct these as follows:
```
>> a = .3; b = .4; n = 4;
>> (1+x)^b * jacpoly(0:n, a, b)
```
However, this currently fails as `singfun` is not able to deal with array-valued `chebtechs`. 
```
Matrix dimensions must agree.
Error in singfun/cancelExponents (line 23)
```
(NB: This error message is not particularly useful.) There's no real reason why this is true, other than that it would be a considerable amount of work to implement for relatively little gain.
This pull request partially addresses support for array-valued functions, although not in a particularly nice way (I try-catch an error in `chebfun/times` and convert the input to a quasimatrix - this probably breaks …
=> feature-array-singfun-hack

aaa.m, tests/chebfun/test_aaa.m
When an element in Z is repeated and one instance of it is chosen as a support point, AAA throws an error because it doesn't drop the appropriate row of the Loewner matrix. This pull request deals with this issue by removing duplicate elements of Z at the start, altogether. I think this is a better strategy than just removing the appropriate indices in the J vector, because it reduces the size of the Loewner matrix that needs to be formed and is therefore more efficient, while remaining mathematically equivalent.
=> Deal with repeated values in Z in AAA

aaa.m, prz.m, reval.m, tests/chebfun/test_aaa.m
As we have seen in numerical experiments, the current contour integral based residue computation can yield low accuracy results when the contour discretization values aren't represented faithfully in floating point arithmetic. This commit instead changes the residue computation to use the identity Res(f/g, z0) = f(z0)/g'(z0), where f and g are analytic at z0. This also obviates difficulties encountered when poles are located close to each other.
=> Improved residue computation

tests/chebfun/test_nodots.m
Fix nodots test (updated MATLAB error message was causing error on R2018a).
=> fix-nodots

ratinterp.m, tests/misc/test_ratinterp.m
The problem was that the lines that build q in this case did not
compensate for the R factor from the QR of the Vandermonde matrix.
Without this, we get embarrassing results like this:
```
>> [p, q, r] = ratinterp(ones(5, 1), 1, 1, [], chebpts(5));
>> p(1)/q(1)
ans =
-4.472135954999578e-01
```
With this commit in place, the result is as expected:
```
>> [p, q, r] = ratinterp(ones(5, 1), 1, 1, [], chebpts(5));
>> p(1)/q(1)
ans =
9.999999999999997e-01
```
This error probably went undetected because the code does compensate for
R when nu > 0, and given how often we play with arbitrary points, it's
conceivable that we just never hit the nu = 0 case in all of our
testing.
=> fix-ratinterp-ratapprox-arbpts

aaa.m
@abigopal and I are in the midst of explorations and development of the AAA-Lawson algorithm in a variety of contexts.  It will greatly facilitate these explorations to have easy access to some Lawson capability, even if it isn't full sorted out yet, when running AAA.  Accordingly we are introducing this for the moment as an undocumented feature (in particular, not mentioned in the AAA help text).  We would hope after a few weeks of exploration and development to have settled on details suitable to be publicizes.
The aim of the AAA-Lawson iteration is to improve a AAA approximant to be close to a minimax approximant.  If you want to run an example, try 
```
X = linspace(-1,1,1000); F = tanh(20*X);
subplot(1,2,1)
r = aaa(F,X,'mmax',16); plot(X,F-r(X)), hold on
r = …
```
=> Aaa lawson experiments

ultrapts.m
Change `flag` from `1` to `0` in order to fix a bug in nodes and weights when `n=720` and `lambda=0.1` in interior region.
Call the new function `gammaratio.m` instead of use `ratioOfGammaFunction` inside.  
Uses REC with orthogonal polynomials instead of orthonormal polynomials because there's a slight improvement in the computations of the weights with orthogonal case.
=> Fix a bug and and make some improvements in ULTRAPTS()

@chebop/matrix.m, tests/chebop/test_matrix.m
Enforce continuity constraints in `chebop/matrix` as suggested in #2278.
As far as I can tell, there are no dependencies on `chebop/matrix' so I'm happy to make this change.
I also adjusted the help documentation a little (but it's still not perfect) and added some tests.
=> fix-chebop-matrix

@trigtech/plotcoeffs.m
This fixes a bug in trigtech-plotcoefffs for constant functions.
```
g = chebfun(@(x)1, 'trig');
plotcoeffs(g)
```
gives the following plot
The new code plots a dot instead of a circle (and is consistent with chebtech/plotcoeffs)
=> fix-trigtech-plotcoeffs for constant functions

chebpts.m
Remove some unnecessary  overheads in `chebfun.chebpts'.
Before:
```
>> tic, for k = 1:1000, chebpts(10); end, toc
Elapsed time is 0.240198 seconds.
```
After:
```
>> tic, for k = 1:1000, chebpts(10); end, toc
Elapsed time is 0.156915 seconds.
```
It's not a huge difference, but it's a trivial change.
=> fix-chebfun-chebpts

@chebfun/conv.m
Simplify the output of `chebfun/conv()`. 
Reasons for doing so: 
* Consistency with old conv method (pre-Legendre series)
* Convolution of two smooth functions typically has a much shorter length than input.
=> fix-simplify-conv

@chebfun/legcoeffs.m, tests/chebfun/test_polyfit.m
Fix this. Add test. 
```
f = chebfun(@(x) sqrt(x+1), 'splitting', 'on');
legcoeffs(f,1)
Index exceeds matrix dimensions.
Error in
chebfun/legcoeffs>legcoeffsPiecewise
(line 76)
out(2,:) = out(2,:) +
sum(diag(w.*z.')*vals);
Error in chebfun/legcoeffs (line
31)
out = legcoeffsPiecewise(f,
varargin{:}); 
```
Closes #2317.
=> legcoeffs(f, 1) failed. Fix that.

@spherefun/sphharm.m
This improves the `sphharm` code by implementing a fast and stable algorithm to compute the values of the associated Legendre polynomials.
The algorithm is no longer based on matlab's `legendre` function and uses the Modified Forward Column method described in the [Holmes and Featherstone paper (2002)](https://link.springer.com/article/10.1007/s00190-002-0216-2).
=> Improve Spherical Harmonics algorithm

@chebfun2/poisson.m, @chebop2/ADIshifts.m, @chebop2/adi.m, @chebop2/adiShifts.m, @chebop2/chebop2.m, @chebop2/fadi.m, @chebop2/setupLaplace.m, tests/chebfun2/test_poisson.m, tests/chebfun2/test_zerofunction.m, tests/chebop2/test_domain.m
This PR adds various solution techniques to `chebfun2/poisson`. In particular, this PR adds the factored ADI method (which can be much faster than the standard ADI method when the rhs is of low rank). For example, 
```
g = chebfun2(@(x,y) x.^2); 
n = 1024;
tic, u = chebfun2.poisson(chebfun2(0), g, n, n, 'adi'); toc
tic, v = chebfun2.poisson(chebfun2(0), g, n, n, 'fadi'); toc
tic, w = chebfun2.poisson(chebfun2(0), g, n, n, 'bartelsStewart'); toc
Elapsed time is 6.113386 seconds.
Elapsed time is 0.293362 seconds.
Elapsed time is 50.693990 seconds.
```
=> Add poisson fadi

@chebfun2/constructor.m, tests/chebfun2/test_constructor2.m
Fix for constructing a `chebfun2` from a row or column vector of values or coefficients (i.e. an `m x 1` or `1 x n` matrix), which gave an error (see #2229). Add some tests.
```
u = chebfun2(rand(2,1));
Operands to the || and && operators must be convertible to
logical scalar values.
Error in chebfun2/constructor>completeACA (line 334)
while ( ( infNorm > absTol ) && ( zRows < width / factor) ...
Error in chebfun2/constructor>constructFromDouble (line 276)
[pivotValue, ~, rowValues, colValues] = completeACA(op,
absTol, 0);
Error in chebfun2/constructor (line 67)
g = constructFromDouble(op, dom, pref, isEqui);
Error in chebfun2 (line 58)
f = constructor(f, varargin{:});
```
=> Fix construction of chebfun2 from univariate data

aaa.m, tests/chebfun/test_aaa.m
In 2018 @abigopal and I put the Lawson iteration into `aaa` as an undocumented feature.  Now we are moving towards making it more robust and adaptive and documented.  In this initial step, the main changes are these: (1) rewritten help text, (2) including rows in the IRLS matrix corresponding to the support points, rather than omitting such rows from the matrix, and (3) automatically invoking Lawson if `'mmax'` is specified and `'lawson'` is not.  Thus if you execute the following code, for example, `aaa` will now automatically try to get you the type (5,5) minimax approximation:
```
X = linspace(-1,1,1000);  F = exp(X);  r = aaa(F, X, 'mmax', 6);  plot(X, F-r(X)), grid on
```
So far, our "adaptivity" consists of just taking 10 Lawson steps!  The next step is to improve this, and also …
=> AAA-Lawson updates

@chebfun2/compose.m, tests/chebfun2/test_trig.m
Fix for `chebfun2` losing `'trig'` on various operations:
```
f = chebfun2(@(x,y) sin(2*pi*x), 'trig')
g = chebfun2(@(x,y) cos(2*pi*x)+2, 'trig')
f + 1 % is not 'trig'
f.^2  % is not 'trig'
f./g  % is not 'trig'
```
Closes #2329.
=> Fix for chebfun2 losing 'trig'

@chebfun2/chebfun2.m, @chebfun2/constructor.m, @chebfun2/disp.m, tests/chebfun2/test_mixed_tech.m
This pull request implements mixed technology in `chebfun2`, i.e., technology that is different in the x- and y-directions. The `chebfun2` constructor has been modified to allow for variations on the arguments `'trig'` / `'periodic'`, `'equi'`, `'coeffs'`, and preferences, in order to specify which dimension the argument refers to. For example, the flag `'trig'` by itself specifies a periodic discretization in both x and y; the new syntax `{'trig', []}` specifies a periodic discretization in x only. The value of the "empty" argument does not matter; the syntax `{'trig', ''}` achieves the same behavior.
Construct a `chebfun2` that is periodic in one dimension. For example:
```
u = chebfun2(@(x,y) ..., {'trig', []});
u = chebfun2(vals_cheb_trig, {[], 'periodic'});
```
Displaying the …
=> Implement mixed technology in chebfun2

aaa.m, tests/chebfun/test_aaa.m
This allows aaa to be called with the degree specified to n, i.e., the output rational function will be of type (n,n). This is done by 
r = aaa(F,Z,'degree',n);
which is equivalent to the previously available 
r = aaa(F,Z,'mmax',n+1);
but to many users degree is more relevant/intuitive, especially with AAA-Lawson refinement (which is now called by default).
=> add degree option to aaa, make sure no clash with mmax

padeapprox.m, tests/misc/test_padeapprox.m
Add option to pass radius when computing coeffs in padeapprox. (Implemented at request of JAC Weideman.)
Allows the easy construction of Pade' approximants of, for example, f = x/(1-x). This was not previously possible as one could not change the radius of the complex valued sampled used to compute the Taylor coefficients of f. (Of course, one could get around this by constructing the coefficients manually.) Now it works directly:
```
[r, a, b, mu, nu, poles] = padeapprox(@(x) x./(1-x), 5, 5, struct('r', 0.5))
>> [r, a, b, mu, nu, poles] = padeapprox(@(x) x./(1-x), 5, 5, struct('r', 0.5))
r =
function_handle with value:
@(z)polyval(a(end:-1:1),z)./polyval(b(end:-1:1),z)
a =
0
1
b =
1.000000000000000
-1.000000000000000
mu =
1
nu =
1
poles =
1.000000000000000
```
Note, I decided to go with …
=> feature-padeapprox-radius

@chebtech/chebtech.m
When running Chebfun in MATLAB 2019b I get the following warning:
```Warning: In the 'chebtech' class, the 'compose' method has both the Abstract attribute and a function body. ```
I think the solution is simply to remove the declaration of `compose` as an abstract method in `@chebtech`, as implemented in this pull request. Although `compose` is implemented in `@chebtech1` and `@chebtech2` these are not *required* as the `@chebtech` method provides the necessary functionality. Therefore `compose` should not be abstract.
=> fix-chebtech-abstract-compose

@trigtech/plotData.m
This should fix the plotting issue raised by @trefethen when plotting the following complex curve:
```
C = chebfun(@(x)exp(1i*pi*x),'trig');
plot(C), axis equal
```
=> Fix the bug of a small gap when plotting a periodic complex chebfun C

@diskfun/roots.m, tests/diskfun/test_roots.m
fixes a few small inconsistencies with `diskfun/roots` and `chebfun2/roots`: 
1. no longer searches for roots across doubled up domain (this was resulting in contours found for negative radius values)
2. returns contours as complex-valued chebfuns, rather than real valued parametrizations.
=> Fix diskfun roots

@chebfun/feval.m, @chebfun/get.m, @chebfun/rdivide.m, tests/chebfun/test_rdivide.m
Avoid spurious NaNs and Infs from removable singularities in `@chebfun/rdivide`.
=> fix-rdivide-spurious-inf-and-nan

smoothie.m
This pull request is created so we have official comments and tracking of the new `smoothie` function introduced by @trefethen.  Here are my comments and questions after reviewing the code:
- Where does the name "smoothie" come from?   My first thought when hearing this name was about a blended frozen fruit beverage.
- There is not a test for smoothie.  It looks like most functions in the chebfun directory have tests.
- The code is quite slow when not using 'trig' mode when the domain is increased.  Here's an example:
```
tic, f = smoothie([-10 10]); toc
Elapsed time is 5.797423 seconds.
tic, f = smoothie([-10 10],'trig'); toc
Elapsed time is 0.057221 seconds.
```
The issue is with line 47, which involves evaluating a trigfun at a very large number of chebyshev points.  This evaluation is …
=> Feature smoothie

@chebfun2/contour3.m, @diskfun/contour3.m, @separableApprox/contour3.m, @spherefun/contour3.m, tests/chebfun2/test_contour3.m, tests/diskfun/test_contour3.m, tests/spherefun/test_contour3.m
This PR implements `contour3` for 2D functions represented by a `separableApprox`.
For a `chebfun2`:
```
f = cheb.gallery2('peaks');
plot(f), hold on, contour3(f, 10, 'k', 'Linewidth', 1)
```
For a `diskfun`:
```
f = cheb.gallerydisk('yinyang');
surf(f), hold on, contour3(f, 10, 'k', 'Linewidth', 1)
```
For a `spherefun` (based on `spherefun`'s "bumpy" plot):
```
f = cheb.gallerysphere('peaks');
subplot(121)
contour3(f, 'Linewidth', 1)
subplot(122)
surf(f, 'projection', 'bumpy'), hold on
contour3(f, 'k', 'Linewidth', 1)
```
=> Implement contour3 for separableApprox objects

@ballfun/fevalm.m
This speeds up the evaluation of a ballfun by a factor of 1.5-2. It should also speed up the code in many places such as quiver for ballfunv.
All the ballfun tests pass.
=> Vectorize ballfun/fevalm to get faster evaluations

@chebop/disp.m
`char(13)` is the ASCII code for a carriage return (CR).  The Command
Window in the MATLAB GUI interprets this as a newline, but most terminal
emulators for Unix-based platforms do not, including xterm, the most
basic and standard terminal emulator that ships with every distribution
of Linux.  This results in a malformed display of chebops for systems of
ODEs when running MATLAB with -nodesktop -nosplash in such environments,
e.g.,
```
>> L = chebop(@(t, y1, y2) [diff(y1) - y1 ; diff(y2) - y2])
L =
Linear operator:
diff(y2)-y2
operating on chebfun objects defined on:
[-1,1]
```
The correct output is:
```
>> L = chebop(@(t, y1, y2) [diff(y1) - y1 ; diff(y2) - y2])
L =
Linear operator:
y1,y2 |--> diff(y1)-y1
diff(y2)-y2
operating on chebfun objects defined on:
[-1,1]
```
Instead of CR, the …
=> Fix newline in chebop.disp() for systems.

aaa.m
This corrects an issue in aaa.m where an automatic selection of sample points (aaa_autoZ) would set the number of Lawson iterations to infinity and thus disable cleanup.
=> Corrects a small error in aaa_autoZ

@chebop2/denseSolve.m
`chebop2` can fail when the discretization sizes in X and Y are not the same, due to a bug in the sizing of Kronecker products. This PR fixes that bug.
The following test was failing, but now passes:
https://github.com/chebfun/chebfun/blob/5fde1a4ab57847c1a0843e88c2b3145bc5410fc9/tests/chebop2/test_generalVariableCoefficients.m#L61-L70
=> Fix incorrect sizing in chebop2 when X and Y discretizations differ

.github/workflows/matlab.yml, tests/singfun/test_feval.m
In this PR I add a `matlab.yml` file to the folder `.github/workflows/`.  This makes chebtest run automatically whenever there is a pull request. In this way, we never have to run chebtest again ourselves (as they run on an ubuntu server supported by GitHub) and GitHub colors the pull-requests (green tick, amber dot, red cross) depending on the status of the testing suite.  
To test this pull request I forked the project, checked the `matlab.yml` file on the forked repo, and then issued a pull request from the forked repo.
=> Never run chebtest again 

@chebfun/spy.m
For a few years Chebfun's `spy` command has produced multicolor lines, though MATLAB's `spy` gives you the standard MATLAB blue color.  I've done a minimal fix so that now Chebfun gives MATLAB blue too.  You can see the difference e.g. with
`cheb.x; spy([x x x])`.
=> making spy lines Matlab-blue

VAeval.m, VAorthog.m, conformal.m, conformal2.m, tests/misc/test_conformal2.m
This introduces a command `conformal2` for conformal mapping of a smooth doubly-connected annular domain onto a circular annulus.  The method is Laurent series implemented with Vandermonde-with-Arnoldi orthogonalization, followed by representation of the conformal maps in both directions by rational functions computed with AAA.
This code was promised in the paper "Numerical conformal mapping with rational functions" by me in _Computational Methods and Function Theory_, 20 (2020), 369-387.  Actually, there it was said to be an option in the `conformal` code, but I've decided to make it a separate code instead.
=> Feature conformal2

minimax.m
This pull request addresses #2399. Fixes a bug that would cause points from outside the approximation domain to be added to the alternating extrema set in some rare occasions.
=> minor fix to minimax

aaa.m
Two references are given in the AAA code. In the second reference the name of the first author was misspelled. Also, it seems the paper appeared in 2020.
=> update second AAA literature reference

@chebfun/idct.m
Fix an inaccuracy in the chebfun.idct help text (specifically how it relates to the idct in the Signal Processing Toolbox).
```
% Note that the above means that chebfun.idct(U) is not the same as idct(U),
% where idct(U) is the implementation in the Matlab signal processing toolbox.
%    The two are related by 
%        idct(U) = CHEBFUN.DCT(E*U)
%    where E = sqrt(n/2)*eye(n); E(1,1) = sqrt(n);
U = rand(5);
n = size(U,1);
E = sqrt(n/2)*eye(n); E(1,1) = sqrt(n);
norm(chebfun.idct(E*U) - idct(U))
ans =
3.9607e-16
```
=> fix-idct-help-text

minimax.m
This pull request addresses #2412. Fixes a bug that would not generate correct p and q polynomials of the minimax rational approximation r when Chebyshev points used to generate p and q map to support points in the barycentric representation of r.
=> fix bug in minimax for computing p and q

@chebfun/whichInterval.m, tests/chebfun/test_trigpade.m, tests/chebmatrix/test_norm.m, tests/chebop2/test_transport.m
Fix a small bug in chebfun.whichInterval()
Before fix:
```
>> chebfun.whichInterval([0 .5 1], 0)
ans =
NaN
```
After fix:
```
>> chebfun.whichInterval([0 .5 1], 0)
ans =
1
```
=> Fix-which- interval

aaa.m, aaatrig.m
AAA has had a problem in approximating functions with singularities.  Poles should be exponentially clustered near the singularities with exponentially decreasing residues, but the "cleanup" procedure was removing them.  This has now been changed so that the test of size of residue is scaled by distance to the approximation set.  The same change was made in AAATRIG.
One complication came up.  Sometimes a pole is right on the boundary of the approximation set, and AAA is usually good at catching this.  To preserve this feature, the scaling of the residue test, which used to involve the maximum size of the function F on the set Z, is not based on the geometric mean size of F on Z.
Various tests have been run to confirm that this change in Cleanup should not have serious effects.  Of course …
=> Feature aaa cleanup

lobpts.m, radaupts.m, tests/misc/test_lobpts.m, tests/misc/test_radaupts.m
The approach we use to compute the Gauss-Legendre-Lobatto nodes in `lobpts` extends to the Jacobi-Lobatto case. The same is true for Gauss-Jacobi-Radau points.
One could solve for the missing weights at the end(s), but there are even explicit formulas (due to Gautschi).
```
>> [x, w, v] = lobpts(4, .2, .7)
x =
-1.000000000000000
-0.338147393222043
0.483074929453927
1.000000000000000
w =
Columns 1 through 2
0.052000500524441   0.644040571638338
Columns 3 through 4
0.859532535973245   0.148340882172585
v =
-0.320698598703037
0.865616354236654
-1.000000000000000
0.455082244466383
```
=> Feature-Gauss-Jacobi-Lobatto-quad

@spinoperator/subsref.m, tests/spinop/test_spinop.m, tests/spinop2/test_spinop2.m, tests/spinop3/test_spinop3.m
If we don't do this, we can't further index properties that are returned without storing them in a separate variable.  This results in unexpected behavior, e.g.,
>> S = spinop('ks');
>> S.domain(2)
ans =
1.0e+02 *
0   1.005309649148734
With this fix in place, we get the expected result:
>> S = spinop('ks');
>> S.domain(2)
ans =
1.005309649148734e+02
=> spin:  Recurse on SUBSREF when accessing properties.

aaa.m, tests/chebfun/test_aaa.m
It has long bothered me that in the aaa code, specifying 'mmax', m is identical to specifying 'degree', m-1, and in particular, it turns on the Lawson iteration.  This is a problem since Lawson isn't (yet!) completely reliable.  
So I've made changes in the AAA code to separate mmax, which now doesn't turn on Lawson, from degree, which does.
For example:
```
X = chebpts(500); F = exp(X);
subplot(121), r = aaa(F,X,'degree',3), plot(X,F-r(X))
subplot(122), r = aaa(F,X,'mmax',4), plot(X,F-r(X))
```
=> revised aaa.m so mmax does not turn on Lawson

@chebfun3/chebfun3f.m
The chebfun3f constructor is now initialized using pseudorandom numbers that are compatible with the chebfun guide.
=> pseudorandom initialization

prz.m
The prz.m code, when the input vector wj contains an entry that is exactly 0, outputs a spurious pole that is not a pole of the rational function. This is because the generalized eigenvalue problem that the prz code is based on proceeds by multiplying the node polynomial to each partial fraction in the barycentric form, then finding the roots of that polynomial. This fix remedies this issue.
=> change prz to remove zero weights to avoid spurious poles

randnfun.m
For large wavelength lambda, randnfun should give results that are nearly constant, but not exactly constant.  For example, this is wrong:
```
>> rng(1), svd(randnfun(100,3))
ans =
2.187063552007912
0.000000000000000
0.000000000000000
```
I've made a change so that now we get more reasonable results:
```
>> rng(1), svd(randnfun(100,3))
ans =
1.033145328179523
0.067353879945334
0.000180359044226
```
The problem was in the "circulant embedding" part of the computation.  randnfun uses a subset of an interval on which a periodic random function is constructed.  It was defining the subset by
```
dom2 = dom(1) + [0 1.2*diff(dom)];
```
but I've changed this to
```
dx = max(0.2,2*lambda/diff(dom));
dom2 = dom(1) + [0 (1+dx)*diff(dom)];
```
=> fix randnfun lambda

@chebfun3/feval.m
This pull request significantly speeds up `chebfun3`'s `feval` when the evaluation points are unstructured (i.e. not a tensor-product grid). See below for a comparison:
```
f = chebfun3(@(x,y,z) sin(x.*y.*z));
n = 50000;
x = 2*rand(n,1)-1;
y = 2*rand(n,1)-1;
z = 2*rand(n,1)-1;
tic
ff = f(x,y,z);
toc
% Before this PR: 2.247853s
% After this PR:  0.028487s
```
=> Vectorize chebfun3/feval in the case of unstructured evaluation points

aaa.m
This is a tweak to AAA-Lawson (namely, underrelaxation) that seems to make a nice difference in suppressing oscillations that stop convergence.  It needs to be explored thoroughly, and may certainly evolve as we do that.  For the moment it's desirable to have it in Chebfun since we're doing a lot of approximation of sign functions for Zolotarev purposes, and the risk is negligible since the tweak only applies to a non-default Lawson option that was introduced just two days ago.
=> tweak to Lawson, only when sign on is specified

aaa.m, tests/chebfun/test_aaa.m
This change to AAA adds a new feature to improve performance in difficult AAA-Lawson cases: `'damping',d` to introduce a damping ratio other than the default of 1.  There will be no effect on codes that do not specify `'damping'`....
...with one small exception: the `'sign'` flag now only affects AAA iteration as before, not AAA-Lawson iteration, since its rather mysterious action in that case is now supplanted by this less mysterious damping option.
See Trefethen unpublished memo Rat348 for illustrations.  This change is likely to be improved upon the future, but for the moment, it increases AAA's ability to get minimax approximations in difficult cases, like the Fermi-Dirac example from Fig. 5 of Nakatsukasa & Trefethen 2020.
Hopefully @heatherw3521 can take a look, and @nakatsukasayuji …
=> AAA Lawson damping

aaa.m, tests/chebfun/test_aaa.m
Removed 10th output in AAA. If 'deriv_deg = k' is specified by the user, r will now be a k+1 element cell array containing the approximation and the first k derivatives.
=> improved syntax in AAA diffbary

@chebfun/resetPointValues.m
Silences an Octave warning.  "resetPointValues" is the correct name b/c its the one mentioned in chebfun.m (and used elsewhere).
=> resetPointValue: rename function to match filename

chebtest.m, tests/chebfun/test_aaa.m
Chebtest will now display which subtests are failing. This makes it easier to diagnose failures that occur on the CI but are not easily reproduced locally.
=> feature-improved-chebtest-display

@chebfun3/chebfun3classic.m, @chebfun3/chebfun3double.m
Comment-only change, found while hacking with `codespell`.
Main change here is there is not `constructionFromDoubles` but rather `constructFromDouble`.
=> Fix up some comments about constructFromDouble

aaa.m, tests/chebfun/test_aaa.m
The `aaa.m` calculation of residues is inaccurate in the sense that much smaller residuals can often be achieved if we replace it by a residue calculation based on a least-squares fit.  This pull request does the replacement.
Approximation of functions with poles at infinity may be problematic.  We don't know everything about calculating residues!  See 
[rat385_residues.pdf](https://github.com/user-attachments/files/22011246/rat385_residues.pdf)
for information justifying (I hope) this change.
=> modified AAA residues calculation

@chebfun/plot.m, @chebfun/plot3.m
Using `handlevis` throws an `Octave:abbreviated-property-match` warning on Octave.  It works fine on either system but it seems we should use the real name (`handlevisibility`), not the abbreviation.
=> don't abbreviate property names
