tests/chebfun/test_trigcasting.m

adjusting a test in trigcasting.

---

@treeVar/expandTree.m
@treeVar/toFirstOrder.m
tests/treeVar/test_toFirstOrder.m

An example by @trefethen was taking very long because of this.

Ensure we include breakpoints arising from the RHS.

---

@chebtech/assignColumns.m
@trigtech/assignColumns.m
tests/chebtech/test_assignColumns.m
tests/trigtech/test_assignColumns.m

fix-chebtech-assignColumns

---

@chebfun/chebcoeffs.m
@singfun/chebcoeffs.m
chebpoly.m
tests/singfun/test_chebcoeffs.m

This partially fixes #1358.
This is branched off of fix-chebpoly.

Fix singfun chebcoeffs

---

@trigtech/plus.m
tests/trigtech/test_plus.m

Fixes #1367 and includes a test.

Fixed bug in trigtech/plus for even length trigtechs.

---

@chebfun/chebcoeffs.m
@chebtech/chebcoeffs.m
@trigtech/chebcoeffs.m

Fix chebcoeffs

---

@chebfunpref/chebfunpref.m

fix-splitMaxLength-docs

---

@chebfun/dct.m
@chebfun/dst.m
@chebfun/idct.m
@chebfun/idst.m
tests/chebfun/test_dct.m
tests/chebfun/test_dst.m

Implemented the missing DCTs, DSTs, IDCTs, and IDSTs of types 5-8.  
I just cannot figure out how to achieve IDST8 in O(N log N)... Any ideas?

Feature dcts5-8

---

@singfun/plotData.m
@singfun/rdivide.m
tests/singfun/test_rdivide.m

Fix singfun rdivide

---

@chebfun/fracDiff.m
@chebfun/fracInt.m
@chebfun/jaccoeffs.m
jac2cheb.m
tests/chebfun/test_fracInt.m

Fix Caputo <-> R-L confusion in fractional differentiation
Also fixes an orientation bug in `jaccoeffs()`.

fix fracDiff

---

@chebfun/horzcat.m
@chebfun/vertcat.m
tests/chebfun/test_horzcat.m
tests/chebfun/test_vertcat.m

Fix chebfun vertcat

---

@operatorBlock/operatorBlock.m

Supersedes #1394.
Closes #1393.

Fixing the diffOrders of operatorBlock.fred and volt.

---

@chebfun/heaviside.m

Fixing inaccuracy in help text of chebfun/heaviside

---

@chebfun/diff.m
@chebfun/get.m
@chebfun/plot.m
@chebfun/plotData.m
@deltafun/deltafun.m
@deltafun/mergeColumns.m
@deltafun/plotData.m

This is how the plot for delta functions will look:
```
f = abs(x) + dirac(x-.5) + heaviside(x+.5) + heaviside(x-.5) + dirac(x-.9) + abs(x-.99)
f =
chebfun column (5 smooth pieces)
interval       length   endpoint values  
[      -1,    -0.5]        2         3        2 
[    -0.5,       0]        2         3        2 
[       0,     0.5]        2         2        2 
[     0.5,    0.99]        2         3        3 
[    0.99,       1]        2         3        3 
Epslevel = 8.483432e-16.  Vscale = 3.010000e+00.  Total length = 10.
Delta functions:
1       1
Locations:
0.5     0.9
plot(f)
```

Fix delta plot

---

@chebfun/chebfun.m
tests/chebfun/test_doubleLength.m

Doublelength should give 2*N-1, not 2*N+1.

---

@trigtech/plotcoeffs.m

Plotting coefficients of even length trigtech

---

@singfun/plus.m
tests/chebfun/test_diff.m
tests/singfun/test_diff.m
tests/singfun/test_minandmax.m
tests/unbndfun/test_diff.m

There is no need to call the constructor when adding singfuns whos exponents differ by an integer

Fix singfun plus 

---

@chebfun/cell2quasi.m
tests/chebfun/test_cell2quasi.m

Fix to quasimatrix construction with doubles. 
Closes #1344.

fix-cell2quasi

---

@singfun/findSingExponents.m
@singfun/singfun.m
tests/singfun/test_singfun_constructor.m

Allow singfun to construct from double. 

---

@chebfun/dst.m
@chebfun/idst.m
tests/chebfun/test_dst.m

DST-II and DST-III were the wrong way around. 
Fixed and improved the implementation.

fix-chebfun-dst

---

@chebfun/chebfun.m
@chebfun/truncate.m
tests/chebfun/test_truncate.m

Add truncate method. Includes test.
Closes #1350.

feature-truncate

---

@chebop/solvebvp.m
@linop/linsolve.m

More meaningful errors and warnings when we encounter incorrect no. of BCs

---

@chebfun/odesol.m
@chebop/solveivp.m

Feature ivp splitting off

---

@adchebfun/adchebfun.m
@chebmatrix/chebmatrix.m
@chebop/chebop.m
@chebop/eigs.m
@chebop/linearize.m
@chebop2/constructBC.m
@linop/linsolve.m
@operatorBlock/operatorBlock.m
tests/chebop/test_linearizationDimensions.m
tests/chebop/test_linearize.m
tests/chebop/test_paramODE_inBCs.m
tests/chebop/test_paramODE_linearization.m

A lot of changes to do more clever things with the dimensions of derivatives in Chebfun.
I'd like to go through this at a Chebfun meeting before merging, as it brings some subtle changes to chebops.
Closes #1176,  #1209 , #1392 (and potentially some more).

Fix derivative dimensions

---

@chebfun/cumsum.m

making the zero mean test at the Chebfun level tighter

---

@chebtech/chebtech.m
@chebtech/lval.m
@chebtech/rval.m
@chebtech1/get.m
@chebtech2/get.m

Add chebtech/lval() and chebtech/rval(). 
Closes #1171.

feature-chebtech-lvalrval

---

legpts.m

fix-legpts

---

@chebfun/eigs.m
@chebfun/expm.m

Feature chebfun eigs expm helptext

---

@adchebfun/taylorTestingBinary.m
@chebmatrix/mtimes.m
tests/chebmatrix/test_matrixOutput.m
tests/linop/test_functionals.m

Enhancement chebmatrix matrix output

---

@chebop/mldivide.m
@chebop/solvebvp.m
@chebop/solveivp.m

This fixes the discrepancy the chebop/mldivide/solveivp/solvebvp documentation discussed in #1457. Since this is a fairly minor fix, regarding only documentation, I'll merge it myself tomorrow evening unless anyone objects.

Fixing unclear documentation, as mentioned in #1457.

---

@chebfun/chebcoeffs.m
@chebfun/jaccoeffs.m
@chebfun/legcoeffs.m
@chebtech/jaccoeffs.m
@fun/jaccoeffs.m
@singfun/jaccoeffs.m
@trigtech/jaccoeffs.m
cheb2jac.m

Add more efficient version of jaccoeffs for chebtech-based chebfuns. 
Also fix a few errors in documentation for related methods.

fix jaccoeffs

---

@chebcolloc2/toFunctionOut.m
@linop/eigs.m

Fix problem in eigs when max dim is reached. 

---

@chebfun/plot.m
tests/chebfun/test_plot.m

This closes #1316.
@mhsnjvd, would you be willing to take a look at this and let me know what you think?

fix-delta-quasi-plot-colors

---

@singfun/plotData.m

Fix singfun plot

---

@chebfun/chebfun.m

Fix a vscale that should be an hscale.

---

@chebop2/constructBC.m
tests/chebop2/test_domain.m
tests/chebop2/test_neumann.m

Fix chebop2 neumann conditions new

---

@chebtech/times.m
tests/chebtech/test_times.m

Changing from length to size in chebtech/times.

---

@chebtech/populate.m
@chebtech/simplify.m
@trigtech/populate.m
@trigtech/simplify.m
tests/cheb/test_revolution.m
tests/chebfun/test_complex.m
tests/chebfun/test_diff.m
tests/chebfun/test_mrdivide.m
tests/chebfun/test_norm.m
tests/chebfun/test_volt.m
tests/chebtech/test_min.m
tests/chebtech/test_rdivide.m
tests/linop/test_eigsGeneralizedSys.m
tests/singfun/test_rdivide.m
tests/unbndfun/test_sum.m

This pull requests builds on the previous pull request #1562. The major change is how coefficient arrays are extended for simplification.

Feature standard chop

---

@chebgui/displayBVPinfo.m

The lines were appearing thin on the latest version of Matlab.

Making linewidth=2 during Newton iteration in chebgui.

---

@chebguiExporterIVP/printOptions.m
@stringParser/pref2inf.m
@ultraS/toValues.m
tests/trigtech/test_any.m

Warning: A value of class "*" was indexed with no subscripts specified.

Suppress warning messages of the form:

---

@chebfun/kron.m
tests/chebfun/test_kronOp.m

Fixing inconsistent behaviour of chebfun/kron with op output.

---

@chebtech/populate.m
@chebtech/sampleTest.m
@smoothfun/smoothfun.m
@trigtech/sampleTest.m

See commit messages for the details.  Thanks to @jaurentz for finding this.

fix-funqui-NaNs

---

@chebtech/simplify.m
@trigtech/simplify.m

As per Asgeir's request, I've updated the documentation in `@chebtech/simplify.m` and `@trigtech/simplify.m`.

updated comments to clarify algorithm

---

@chebfun/chebpade.m
ratinterp.m

changing the output order

---

@chebop/chebop.m
@chebop/linearize.m
@linop/fitBCs.m
tests/chebop/test_linearizationDimensions.m
tests/chebop/test_zerothOrder.m

This allows solving "zeroth order differential equations", e.g.
```
% Find u and v on [-1, 1] s.t. u^2 - x + sin(v) = v + exp(v) + u = sin(4x)+2
x = chebfun('x');
f = sin(4*x) + 2;
N = chebop(@(x,u,v) [u.^2 - x + sin(v); v + exp(v) + u]);
[u, v] = N\[f; f];
norm(N(u,v)-[f;f])
plot([u v])
```
giving the following result:
```
ans =
1.6699e-13
```
Also, this closes #1437 .

Feature function iteration

---

ultrapts.m

Intending to collaborate on #1645 I added the following: ULTRAPTS() calls LEGPTS() if `lambda=0`, and JACPTS() calls ULTRAPTS() if `-.5<alpha=beta<.5`, `alpha~=0`. See #1651.

Special cases in JACPTS(), and in ULTRAPTS().

---

jacpts.m

JACPTS() calls ULTRAPTS() if `-.5<alpha=beta<.5`, `alpha~=0`.
See #1645 and #1650.

JACPTS() calls ULTRAPTS()

---

@chebop/chebop.m
@chebop/quiver.m
@chebop/solvebvp.m
@chebop/solveivp.m

Since these are just documentation updates, I'll merge this myself before the meeting this afternoon unless someone objects.

Documentation quiver multouts

---

@chebfun/disp.m
@chebfun2/disp.m

Unify 1D and 2D displays to address issue #1646.

---

@chebfun/remez.m
tests/chebfun/test_remez.m

Fix remez for zero function. 

---

@chebgui/solveGUIpde.m
@chebguiExporterPDE/printPostSolver.m
chebguiDemos/pdedemos/ks.guifile
chebguiWindow.m

This leads to significant speed improvements.
See discussions in #1648, although this doesn't deal with the storing of PDE solutions (should be done on a separate branch).

Don't specify linewidth for waterfall plots.

---

lebesgue.m
tests/misc/test_lebesgue.m

Add a simplify call at the end of lebesgue().

---

@chebfun/chebfun.m
lebesgue.m
tests/chebfun/test_vectorCheck.m
tests/misc/test_lebesgue.m

Fix vectorcheck

---

@valsDiscretization/scale.m

Fix chebcolloc.scale.

---

@chebmatrix/deal.m
tests/chebop/test_multOutputs_simplify.m

Fix chebop multiple outputs simplify

---

@chebop/quiver.m
tests/chebop/test_quiver.m

* Set default domain for chebop/quiver.
* Simplify specifying properties of lines for quiver plots.
Based on suggestions by @trefethen .

Default domain and linespec improvements for chebop/quiver

---

@trigtech/plotcoeffs.m

Fixes bug with setting the x-axes limits for a length 1 trigtech.
Closes #1692.

Fix trigtech plotcoeffs for length 1 trigtech

---

@chebguiExporterEIG/printSetup.m

Add missing space in CHEBGUI chebeig.m ouput.

Fix chebeig

---

@separableApprox/plotcoeffs.m

Put the two figures from `chebfun2/chebcoeffs` into subplots.

Put the two figures from `chebfun2/chebcoeffs` into subplots.

---

jacpts.m

Small change in jacpts() for clarity.

fix-jacpts-trivial

---

@chebfun/disp.m

Some small improvements to `chebfun/disp()`.
Closes #1679.

Fix chebfun disp

---

@chebfun/odesol.m

Previously, problems such as
```
u0 = 0; v0 = 3; w0 = 4i; N = chebop(0,150);
N.op = @(t,u,v,w) [ ...
diff(u,2) + (u-v)/abs(u-v)^3 + (u-w)/abs(u-w)^3; ...
diff(v,2) + (v-u)/abs(v-u)^3 + (v-w)/abs(v-w)^3; ...
diff(w,2) + (w-u)/abs(w-u)^3 + (w-v)/abs(w-v)^3];
N.lbc = @(u,v,w) [u-u0; v-v0; w-w0; diff(u); diff(v); diff(w)];
[u,v,w] = N\0
```
would require the user to turn `splitting on` in order for the `chebfun` constructor to successfully converge to a piecewise solution. With this PR, we first try to construct a global representation of the solution, but if that fails, we attempt again with splitting on. Note that the ODE solution is only computed once, the only extra work is another call to the `chebfun` constructor (i.e. we don't have to call `ode113` twice).

If we end up with an unhappy chebfun when solving IVP, try with splitting on.

---

@treeVar/splitTree.m

Make call to splitTree static.

---

@separableApprox/simplify.m

Add tolerance to 2D simplify.

---

@singfun/cumsum.m
@singfun/extractBoundaryRoots.m
@singfun/replaceBoundaryRoots.m
tests/bndfun/test_cumsum.m
tests/chebfun/test_cumsum.m
tests/unbndfun/test_cumsum.m

Fix singfun cumsum

---

diffmat.m

Adding 'trig' flag to diffmat.

---

tests/misc/test_trigBary.m
trigBary.m
trigBaryWeights.m

fix-trigBary

---

cheb2jac.m
jac2cheb.m
tests/misc/test_cheb2jac.m
tests/misc/test_jac2cheb.m

Deal with the special cases of `alpha=beta=-0.5` and `alpha=beta=0.5`, which are simply diagonal and banded scalings, respectively.

Fix jac2heb

---

@chebfun/chebfun.m
@chebfun/compose.m
@chebfun/inv.m
@chebfun/tolUnion.m
@chebfun/tolUnique.m
fov.m

These commits attempt to fix a few minor breakpoint-related issues that are the source of the issue Prof. Greenbaum sent us today regarding her trouble with `fov()`.  Credit to @nickhale.

fix-breakpoint-issues

---

@separableApprox/plus.m

Small increase in tolerance in Chebfun2's compression plus algorithm

---

@chebfun/qr.m
@chebfun/quasi2cheb.m
@chebtech/qr.m
tests/chebfun/test_mldivide.m
tests/chebfun/test_mrdivide.m
tests/chebfun/test_orth.m
tests/chebfun/test_qr.m

There are two components to this PR:
1) Computing in coefficient space at the `chebtech` level (speak to @jaurentz about this and see #1542 )
2) For `chebfun` objects of multiple pieces, computing the QR factorization of each piece independently and then recombining the result.
These two can be separated if necessary.
Edit: Thanks to @jaurentz and @aaustin141 for useful discussions on this.

Feature improved qr

---

lebesgue.m
tests/misc/test_lebesgue.m

feature-trig-lebesgue

---

standardChop.m

This pull request fixes the issue in #1793.

updated standardChop to use cummax

---

@linop/expm.m
tests/linop/test_expm.m

This pull request fixes the problem in #1790.

Fix expm system bug

---

@chebfun2/constructor.m
tests/chebfun2/test_constructor2.m

This addresses #1801. A test is also added to check this.

Fix chebfun2 constructor lengths #1801

---

@separableApprox/transpose.m

Update the domain of chebfun2 object at transpose

---

@spherefun/constructor.m
tests/spherefun/test_composition_operators.m
tests/spherefun/test_constructor.m
tests/spherefun/test_sphharm.m

This pull request address #1783 and #1785.  The Spherefun constructor now uses similar input parsing to the Chebfun2 constructor.  Thanks to @nickhale for refactoring the Chebfun2 constructor.  This made the refactoring for Spherefun much easier.

Fix spherefun constructor input parasing

---

@chebfun2/constructor.m
tests/chebfun2/test_constructor2.m

Fixes #1824 and the other problems raised by @ajt60gaibb under this issue.  Closes #1824.

Fix chebfun2 constructor fixed rank, fixed length, and domain input parsing

---

@chebfun/jaccoeffs.m
@singfun/fracInt.m
tests/chebfun/test_ultracoeffs.m
ultracoeffs.m

Nothing fancy. Just a wrapper for `jaccoeffs()`, but it's useful to me and saves having to manually adjust the coefficients each time.
Includes a basic test.

Add a basic ULTRACOEFFS() code.

---

jacpts.m
ultrapts.m

1. `JACPTS()` calls `ULTRAPTS()` if` ALPHA = BETA` for `ALPHA > -1` and `ALPHA ~= -.5, 0, .5`;
2. Add some comments about range of `LAMBDA`.

JACPTS() calls ULTRAPTS() for ALPHA=BETA and ALPHA > -1

---

jac2jac.m

```
seedRNG(0);
c = rand(1000, 200);
tic
jac2jac(c, .4, .2, .7, 3);
toc
% Elapsed time is 2.041306 seconds. (Development)
% Elapsed time is 1.226177 seconds. (This branch)
```

Vectorise jac2jac implementation.

---

@separableApprox/fevalm.m
tests/chebfun2/test_fevalm.m
tests/spherefun/test_fevalm.m

The code for `separableApprox/fevalm` was left unfinished but working. Finish.

Tidy and add test for separableApprox/fevalm.m 

---

@chebfun2/constructor.m

See #1771; this is just a re-doing of @ajt60gaibb's commit from there to work in the world of #1765.

fix-chebfun2-grids-v2

---

@chebfun/plotcoeffs.m
@chebtech/plotcoeffs.m
@trigtech/plotcoeffs.m

Implement wave number scaling for trigtechs.

---

@spherefun/gaussfilt.m
tests/spherefun/test_gaussfilt.m

Name change of command `spherefun/smooth` to `spherefun/gaussfilt`.

Smooth to gaussfilt

---

@chebcolloc2/chebcolloc2.m
@chebdouble/chebdouble.m
@chebfun/pdeSolve.m
@domain/volt.m

Fix the Volterra operator in a couple of places.

fix-pde15s-volt

---

@spherefun/svd.m

@gradywright's improvement. 
There is no need to set `n = max(2*length(A), 30)` in `spherefun/svd` for the quadrature rule to calculate inner-products. Instead, one can use `n = length(A) + 9`.  This small changes slightly improves the efficiency of `spherefun/svd`. For example, 
```
% development branch:
f = spherefun(rand(100)); 
tic, v = svd( f ); toc 
Elapsed time is 0.326853 seconds.
% improve-spherefun-svd branch:
f = spherefun(rand(100)); 
tic, v = svd( f ); toc 
Elapsed time is 0.266533 seconds.
```

Improve spherefun svd

---

@coeffsDiscretization/coeffsDiscretization.m

This method should not be static.

fix-cumsum-in-ultraS-error-message

---

@chebfun2/coeffs2.m
@chebfun2/constructor.m
@separableApprox/length.m
@spherefun/constructor.m
tests/chebfun2/test_zerofunction.m
tests/spherefun/test_coeffs2.m
tests/spherefun/test_constructor.m

```
% In development: 
f = chebfun2( zeros(5,4) );
coeffs2(f)
ans =
0
% In branch: 
f = chebfun2( zeros(5,4) );
coeffs2(f)
ans =
0     0     0     0
0     0     0     0
0     0     0     0
0     0     0     0
0     0     0     0
```
Closes #1802.

Fix chebfun2 zero matrix

---

@spherefunv/quiver.m

Fix hold on bug in spherefunv/quiver.m

---

@spherefun/sphharm.m
tests/spherefun/test_sphharm.m

The spherical harmonics in Spherefun should be orthonormal.

Fix spherical harmonics normalization

---

@domain/polyfit.m
tests/domain/test_polyfit.m

```
v = rand(10000,1);
D = domain([-1,1]);
% On development: 
tic, f = polyfit( linspace(-1,1,10000), v, 100, D); toc
Elapsed time is 0.605382 seconds.
% On branch: 
tic, g = polyfit( linspace(-1,1,10000), v, 100, D); toc
Elapsed time is 0.103300 seconds.
norm( f - g ) 
ans =
1.229515606844055e-15
```

Trivial speed up of polyfit.

---

@chebfun/log.m
@chebfun2/log.m
@chebfun2/max.m
@chebfun2/min.m
@separableApprox/log.m
@separableApprox/max.m
@separableApprox/min.m
@spherefun/log.m
@spherefun/max.m
@spherefun/min.m

Improve chebfun2 help text

---

@chebtech/roots.m

Some very minor tidying of code in `chebtech/roots`.

fix-chebtech-roots

---

@singfun/sample.m

Presumably this isn't being called anywhere..

Fix singfun/sample.

---

+cheb/gallery3.m
@chebfun3/norm.m
@chebfun3t/display.m
@chebfun3t/power.m
@chebfun3t/rdivide.m
@separableApprox/norm.m
tests/chebfun2/test_norm.m
tests/chebfun3/test_norm.m

This closes #1937, #1938, and #1939.

Fix #1937, #1938, and #1939

---

@chebfun/pde15s.m
@chebfun/pdeSolve.m

Fix parsing of multiple options to pdeSolve.

fix-pdeSolve-parsing

---

@chebfun3/laplacian.m
@chebfun3v/laplacian.m

Addresses #1941 .
Additionally, this allows to compute the Laplacian of a chebfun3v with 2 components.

Fix chebfun3v simplify laplacian

---

@chebfun2/eig.m
outerProd.m

This closes issues #1988 and #1987.

correct outerProd and chebfun2eig

---

tests/chebfun2v/test_integral.m

Add a test for chebfun2v/integral().

---

@chebfun3/abs.m
@chebfun3/chebfun3.m
@chebfun3/jacobian.m
@chebfun3/log.m
@chebfun3/power.m
@chebfun3/private/singleSignTest.m
@chebfun3/sqrt.m
@separableApprox/abs.m
@separableApprox/log.m
@separableApprox/power.m
@separableApprox/singleSignTest.m
@separableApprox/sqrt.m
tests/chebfun3/test_plotting.m

Closes several small issues in chebfun3 (and separableApprox):
#1998, #1999, #2000, #2002 and #2003

Fix singleSingTest

---

@chebfun3/plot.m
tests/chebfun3/test_plotting.m
tests/chebtech/test_minus.m

This allows plotting chebfun3 objects on non-standard domains motivated by the ideas of Rodrigo Platte.

Chebfun3 plot

---

aaa.m
tests/chebfun/test_aaa.m

This pull requests adds the command `aaa(F, Z)` for AAA rational approximation.

AAA rational interpolation

---

@diskfun/harmonic.m
tests/diskfun/test_harmonic.m

This makes the help text for the `diskfun.harmonic` more clear.

adjust help text and include additional test

---

cheb2leg.m
ultracoeffs.m

Fix ultracoeffs for array-valued input.

fix-ultracoeffs

---

@diskfun/constructor.m
@spherefun/constructor.m
tests/diskfun/test_constructor.m
tests/spherefun/test_constructor.m

This PR fixes a bug in the `diskfun` and `spherefun` constructors where the vectorize flag was not being checked correctly.

Fix spherefun and diskfun vectorize

---

@chebfun/trigremez.m
tests/chebfun/test_trigremez.m

This branch implements a Remez algorithm for best trigonometric rational approximation of a chebfun

code for rational trigremez

---

@spinop/initializeMovie.m
@spinop2/initializeMovie.m
@spinop3/initializeMovie.m
spin.m
spin2.m
spin3.m

Fix the title problem in SPIN.

---

@chebtech/times.m
tests/chebtech/test_times.m

Ensure correct (max) degree for polynomial multiplication.
New test included.

featre-chebtest-times

---

@chebfun/truncate.m
tests/chebfun/test_truncate.m

Fix trigfun trunc

---

@chebfun/remez.m

The domain for the denominator when trying to compute type (0,0) approximations was not correctly set.

small bug when doing (0,0) approximations

---

@adchebfun/adchebfun.m

fix-adchebfun-vectorizeOp

---

@chebfun/diff.m

added error message for diff(F,G)

---

@chebfun2/constructor.m
tests/chebfun2/test_trig.m

Fixes #2097. Closes #2097.
Now, 
```
f = chebfun2(coeffs,'coeffs', 'trig');
```
should work.

Fix chebfun2 trig string

---

@separableApprox/minandmax2.m

Closes #2093.   Now, we have 
```
cheb.xy
tic, max2(x); toc
Elapsed time is 0.055512 seconds.
```

Simplify the chebfun slices of a rank-1 2D function before finding their roots.

---

@separableApprox/subsref.m

```
f = chebfun2(@(x,y) x);
>> f(0)
Error using separableApprox/subsref (line 77)
Object is a function of two real variables
```

Give error for f(x) if isreal(f) = 1 and isreal(x) = 1.

---

@chebfun/arrowplot.m

* Introduce 'markerSize' option for arrowplot (case insensitive)
* Return both arrow and line graphic objects.
* Cleanup of logic for parsing inputs.
Closes #2103.

Arrowplot improvements

---

ODEformats.m
randnfun.m
randnfun2.m
randnfun2trig.m
randnfunold
randnfuntrig.m
tests/misc/test_randnfun.m
tests/misc/test_randnfun2.m
tests/misc/test_randnfun2trig.m
tests/misc/test_randnfuntrig.m

We can now do 2D random functions, both periodic and nonperiodic.  Arbitrary rectangular domains are supported.

Feature randnfun2

---

@chebguiExporterBVP/printSetup.m
@chebguiExporterIVP/printSetup.m

Fix syntax for initial guesses when export systems to m files.

---

@chebfun/conv.m
tests/chebfun/test_conv.m

Add quasimatrix support for CONV().

feature-quasimatrix-conv

---

+cheb/gallerysphere.m
@spherefun/conj.m
@spherefun/constructor.m
@spherefun/sphharm.m
@spherefun/std2.m
randnfun.m
randnfunsphere.m
tests/misc/test_randnfunsphere.m

This pull request introduces the `randnfunsphere` function for generating random functions on the sphere.  It is a companion to the `randnfun` and `randnfun2` functions.

Feature randnfunsphere

---

@chebfun2/plot.m
@chebfun2/surf.m
@diskfun/plot.m
@separableApprox/plot.m
@spherefun/plot.m

This includes a 'zebra' option in the `plot` commands in Chebfun2, Spherefun, and
Diskfun.  Here are some fun things to try:
```
cheb.xy; plot(randnfun2(.1)+x, 'zebra'), axis equal
plot(randnfunsphere(.1), 'zebra')
cheb.xydisk; plot(sin(30*x.*(1+y)), 'zebra')
```

Feature zebraplot

---

aaa.m
tests/chebfun/test_aaa.m

Adds support for string inputs in aaa. See also #2124.

Support for string inputs in aaa

---

@chebfun2/constructor.m
tests/chebfun2/test_constructor.m

Allow chebfun2('1'), etc.

---

@separableApprox/cdr.m

Treat Inf and -Inf the same in the CDR factorization

---

@chebfun/integral.m
@chebfun/sum.m
tests/chebfun/test_sum.m

Better fix to #2149.
See also #2150.

Fix chebfun sum

---

@chebfun/inufft.m
@chebfun/nufft.m
@chebfun/nufft2.m
@spherefun/fastSphereEval.m

Tidy `nufft` and related code (mainly cosmetic changes).

tidy-nufft

---

@chebfun/chebfun.m

I've made a very small change trying to address issue #2114 . It consists of vectorizing an input, instead of transposing it.

Vectorizing e.g. 1/(2-x)

---

@spinoperator/solvepde.m
spincomp.m

Fix the spincomp code 

---

@trigtech/flipud.m
tests/trigtech/test_flipud.m

Fixes bug in `flipud` for even length `trigtechs`.  Closes #2170.

Fix trigtech flipud

---

@imex/computeCoeffs.m
@imex/imex.m
@imex/oneStep.m
@imex/startMultistep.m
@spinoperator/solvepde.m
@spinpref/spinpref.m
@spinpref2/spinpref2.m
@spinpref3/spinpref3.m
@spinprefsphere/spinprefsphere.m
tests/spinopsphere/test_spinsphere.m
tests/spinscheme/test_startMultistep.m

Implement multistep scheme `imexbdf4` as an alternative of `lirk4`.

Feature spinsphere imexbdf4

---

@chebfun/arrowplot.m

Feature arrowplot multi

---

@chebfun/cummax.m
@chebfun/cummin.m
tests/chebfun/test_cummax.m
tests/chebfun/test_cummin.m

This pull request addresses #2174 and implements cummax and cummin commands for chebfun arguments.

Feature cummax

---

@treeVar/treeVar.m
tests/chebop/test_intops.m

Fix 'IVPs' with Fredholm or Volterra terms.
Closes #2179 and #2122.

Fix-fred-ivp

---

@trigtech/horner.m
tests/trigtech/test_feval.m

Bug fix for evaluation of a complex, constant trigtech

---

@chebfun/besseli.m

This pull request solves #1936 by correcting a small bug in the computation of besseli functions.

small bug in besseli computation

---

@expinteg/computeCoeffs.m
@expinteg/expinteg.m
@expinteg/gammaEval.m
@expinteg/gammaFun.m
@expinteg/oneStep.m
@expinteg/phiEval.m
@expinteg/phiFun.m
@expinteg/psiEval.m
@expinteg/startMultistep.m
@imex/imex.m
@spinoperator/solvepde.m
@spinpref/spinpref.m
@spinpref2/spinpref2.m
@spinpref3/spinpref3.m
@spinscheme/spinscheme.m
spin.m
spin2.m
spin3.m
tests/spinscheme/test_phiFun.m

Hotfix rename expint

---

randnfun2.m
tests/misc/test_randnfun2.m

This change makes the `randnfun2` code consistent with `randnfun` (see pull request #2225).

Change 'norm'  to 'big' in randnfun2

---

cheb2jac.m

fix-cheb2jac

---

minimax.m
tests/misc/test_minimax.m

This pull request fixes issue #2244.

fix for issue #2244

---

@chebfun/inufft.m
@chebfun/nufft.m
@chebfun/nufft2.m
tests/misc/test_inufft.m
tests/misc/test_nufft.m

- Removed another unnecessary NUFFT-I call.  
- Re-organized the code and added comments to explain a bit more about the math behind the code.
- Fixed the planning code for INUFFT-II and added a planning version of INUFFT-I.
- Fixed #2258 
- Added some more tests

Tiny speed-up and clean-up of inufft

---

chebvals2legvals.m

Small fix to chebvals2legvals.

fix-chebvals2legvals-trivial

---

@chebfun2/end.m
@separableApprox/end.m
tests/chebfun2/test_end.m

Add chebfun2/end method and test.
Closes #2282.

feature-chebfun2-end

---

@ultraS/multmat.m

No tests at the moment. I cannot remember where the ultraS tests are...

Bug in ultraS.multmat for lambda>1 and high degree variable coeffs. 

---

lagpoly.m
tests/misc/test_lagpoly.m

Add support for generalized Laguerre polynomials.

feature-gen-poly

---

@chebfun/besselj.m
tests/chebfun/test_besselj.m

Add support for besselj(0:3, x)

fix-besselj

---

gammaratio.m
lagpts.m
tests/misc/test_lagpts.m

* Reinstate GLR
* Add new REC
* Adjust default methods. 
See #2270 for discussion.
% Determine default method (heuristic):
n < 300 = rec
n < 1000 = gw
n < 3000 & alpha ~= 0 = gw
n < 3000 & alpha = 0 = glr
n > 3000 = RH

fix-lagpts

---

@classicfun/get.m
tests/chebfun/test_points.m

Ensure get(f, 'points') scales points to correct domain.
Test added.

fix-chebfun-points

---

@bndfun/conv.m
tests/chebfun/test_conv.m

Resort to quadrature approach when there are many patches required in convolution due to vastly different domain sizes. (Previously we just threw an error.)
Also tidied the code and added some tests.

Fix-chebfun-conv

---

@chebfun2/coeffs2.m
tests/chebfun2/test_zerofunction.m

Fix bug in chebfun2/coeffs2 

---

@chebtech/clenshaw.m

Don't use deal in Clenshaw. Too much overhead.

feature-dont-use-deal-in-clenshaw

---

jacpts.m
tests/misc/test_jacpts.m
ultrapts.m

Fix some problems in `jacpts` pointed out by Javier Segura.

fix-jacpts

---

@spherefun/surf.m

This PR implements "bumpy" surface plots for `spherefun`, in which the radial component is bumped out according to the function values.
```
f = cheb.gallerysphere('moire');
subplot(121), surf(f)
subplot(122), surf(f, 'projection', 'bumpy')
```

Implement bumpy spherefun plotting

---

@chebfun/pdeSolve.m
tests/misc/test_pde15s.m

Fix pde15s/pde23t for periodic problems (see also #2349).

fix-pdesolve-periodic

---

@linop/fitBCs.m
tests/chebop/test_intops.m

Fix an issue with integral operators. Closes #2360.
```
K = @(x,y) 1+0*x;
N = chebop(@(x,u) - u + exp(x) + 1/3*x*(1-exp(3*x)) + x*volt(K, u^3), [0, 1]);
u = N\0;
norm(u-chebfun(@exp, [0 1]))
ans =
8.2789e-13
```

fix-intops

---

@adchebfun2/adchebfun2.m

I've never done this before, so let me know if I messed up/need to change something.

writing more helpful error message for chebfun2 * adchebfun2

---

@chebfun2/plot.m
phaseplot.m

I've written a short code `phaseplot` to product phase portraits.  (This is essentially the code `wegert` I've been using in my personal work in recent months.)  Examples of use are given in the help text.

New phaseplot.m

---

phaseplot.m

@nakatsukasayuji, I would be grateful if you would review this improvement version of `phaseplot` (with smoothed colors as compared with Wegert's original).  You'll note that this branch is now called `feature-phaseplot-colors2` rather than `feature-phaseplot-colors`.  That's because I made a mistake I was unable to fix with my version of `feature-phaseplot-colors` -- which I will now accordingly delete.

Feature phaseplot colors2

---

phaseplot.m

Fix https://github.com/chebfun/chebfun/issues/2376 and we can now plot the angles with any convention [theta, theta+2*pi].

fix the color range of phaseplot

---

@chebfun/merge.m
tests/chebfun/test_merge.m

Fix scale invariance in chebfun.merge. Closes #2381

fix-chebfun-merge-invariance

---

leg2cheb.m

Correct typo in leg2cheb documentation.

fix-leg2cheb-docs

---

@separableApprox/mtimes.m
tests/chebfun2/test_times.m

Fix chebfun2 mtimes

---

hermpts.m

Update derivative values after Newton iteration has converged in hermpts_rec.
Closes #2394

minor-fix-hermpts

---

@adchebfun/adchebfun.m
@blockFunction/blockFunction.m
@chebcolloc/compose.m
@chebfun/compose.m
@chebfun/feval.m
@opDiscretization/matrix.m
@operatorBlock/operatorBlock.m
@treeVar/treeVar.m
tests/chebop/test_pantograph.m
tests/chebop2/test_transport.m

Add functionality for solving pantograph-type delay differential equations via Chebop.
(See `tests/chebop/test_pantograph.m` for some examples. An Example to be added soon.)

Feature-pantograph

---

@chebfun3/plus.m
tests/chebfun3/test_plus.m

Ensure chebfun3/plus works fine with objects of different tech. 
Also added a test which did not work previously

improve-chebfun3-plus

---

chebpoly.m
tests/chebfun/test_chebpoly.m

Fix chebpoly

---

aaa.m

I am planning to refactor `aaa.m` in the upcoming weeks.  This pull request, however, is not related to that (and the syntax may ultimately change when we refactor).  It adds an option `sign` to the aaa call to invoke a different use of the SVD which @nakatsukasayuji and I have found works much better for sign functions.  It also applies this option in the Lawson phase of AAA, if `lawson` as well as `sign` has been specified.
When we refactor, and after we have learned more, there is a chance we will want to make this or something like it the AAA default.  For the moment, however, the default operation is unchanged and `sign` is simply a new option.  Definitely worth using if you are approximating sign functions or similar!

adding the sign SVD modification option to aaa.m

---

@bndfun/conv.m
legpts.m

Fix convolution so that the legpts argument is integer.

---

.github/workflows/matlab.yml
@chebop2/denseSolve.m
gpr.m
tests/chebfun/test_aaatrig.m
tests/chebfun/test_plot_xylim.m
tests/chebfun2/test_CLA.m
tests/chebop2/test_domain.m
tests/chebop2/test_waveequation.m
tests/chebtech2/test_alias.m
tests/misc/test_gpr.m
tests/spherefun/test_optimization.m

@nickhale here's a branch for changes need to get tests passing on R2025a.  Feel free to push directly to this  `2025a_fixes` branch., or if you prefer, send PR against this.

fixes/changes for tests to pass on R2025a

---

@bndfun/conv.m
tests/chebfun/test_conv.m

Fix for Issue #2456
